
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem TOLproblem97)
    (:domain TOL)

    (:objects
        
    )

    (:init
        (free-loc_0_0 )
        (at-b_0-loc_1_0 )
        (at-b_1-loc_1_1 )
        (clear-b_1 )
        (at-b_2-loc_2_0 )
        (free-loc_2_1 )
        (free-loc_2_2 )
        (clear-b_2 )
    )

    (:goal
        (and (at-b_1-loc_2_0 ) (and (at-b_2-loc_1_0 ) (at-b_0-loc_0_0 )))
    )

    
    
    
)

