
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain TOL)
    (:requirements :equality)
    (:types
        
    )

    (:constants
        
    )

    (:predicates
        (free-loc_0_0 )
        (free-loc_1_0 )
        (free-loc_1_1 )
        (free-loc_2_0 )
        (free-loc_2_1 )
        (free-loc_2_2 )
        (clear-b_0 )
        (clear-b_1 )
        (clear-b_2 )
        (at-b_0-loc_0_0 )
        (at-b_1-loc_0_0 )
        (at-b_2-loc_0_0 )
        (at-b_0-loc_1_0 )
        (at-b_1-loc_1_0 )
        (at-b_2-loc_1_0 )
        (at-b_0-loc_1_1 )
        (at-b_1-loc_1_1 )
        (at-b_2-loc_1_1 )
        (at-b_0-loc_2_0 )
        (at-b_1-loc_2_0 )
        (at-b_2-loc_2_0 )
        (at-b_0-loc_2_1 )
        (at-b_1-loc_2_1 )
        (at-b_2-loc_2_1 )
        (at-b_0-loc_2_2 )
        (at-b_1-loc_2_2 )
        (at-b_2-loc_2_2 )
    )

    (:functions
        
    )

    

    
    (:action move_0
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_1_1 ) (at-b_1-loc_2_0 )) (at-b_2-loc_1_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (clear-b_2 )
        (free-loc_1_1 ))
    )


    (:action move_1
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_1_1 ) (at-b_1-loc_2_1 )) (at-b_2-loc_1_0 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (clear-b_2 )
        (free-loc_1_1 ))
    )


    (:action move_2
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_2_1 ) (at-b_1-loc_1_0 )) (at-b_2-loc_2_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (clear-b_2 )
        (free-loc_2_1 ))
    )


    (:action move_3
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_2_2 ) (at-b_1-loc_1_0 )) (at-b_2-loc_2_1 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (clear-b_2 )
        (free-loc_2_2 ))
    )


    (:action move_4
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_1_1 ) (at-b_2-loc_2_0 )) (at-b_1-loc_1_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (clear-b_1 )
        (free-loc_1_1 ))
    )


    (:action move_5
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_1_1 ) (at-b_2-loc_2_1 )) (at-b_1-loc_1_0 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (clear-b_1 )
        (free-loc_1_1 ))
    )


    (:action move_6
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_2_1 ) (at-b_2-loc_1_0 )) (at-b_1-loc_2_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (clear-b_1 )
        (free-loc_2_1 ))
    )


    (:action move_7
     :parameters ()
     :precondition (and (and (and (and (and (at-b_0-loc_2_2 ) (at-b_2-loc_1_0 )) (at-b_1-loc_2_1 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (clear-b_1 )
        (free-loc_2_2 ))
    )


    (:action move_8
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_1_1 ) (at-b_0-loc_2_0 )) (at-b_2-loc_1_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (clear-b_2 )
        (free-loc_1_1 ))
    )


    (:action move_9
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_1_1 ) (at-b_0-loc_2_1 )) (at-b_2-loc_1_0 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (clear-b_2 )
        (free-loc_1_1 ))
    )


    (:action move_10
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_2_1 ) (at-b_0-loc_1_0 )) (at-b_2-loc_2_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (clear-b_2 )
        (free-loc_2_1 ))
    )


    (:action move_11
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_2_2 ) (at-b_0-loc_1_0 )) (at-b_2-loc_2_1 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (clear-b_2 )
        (free-loc_2_2 ))
    )


    (:action move_12
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_1_1 ) (at-b_2-loc_2_0 )) (at-b_0-loc_1_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (clear-b_0 )
        (free-loc_1_1 ))
    )


    (:action move_13
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_1_1 ) (at-b_2-loc_2_1 )) (at-b_0-loc_1_0 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (clear-b_0 )
        (free-loc_1_1 ))
    )


    (:action move_14
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_2_1 ) (at-b_2-loc_1_0 )) (at-b_0-loc_2_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (clear-b_0 )
        (free-loc_2_1 ))
    )


    (:action move_15
     :parameters ()
     :precondition (and (and (and (and (and (at-b_1-loc_2_2 ) (at-b_2-loc_1_0 )) (at-b_0-loc_2_1 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (clear-b_0 )
        (free-loc_2_2 ))
    )


    (:action move_16
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_1_1 ) (at-b_0-loc_2_0 )) (at-b_1-loc_1_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (clear-b_1 )
        (free-loc_1_1 ))
    )


    (:action move_17
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_1_1 ) (at-b_0-loc_2_1 )) (at-b_1-loc_1_0 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (clear-b_1 )
        (free-loc_1_1 ))
    )


    (:action move_18
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_2_1 ) (at-b_0-loc_1_0 )) (at-b_1-loc_2_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (clear-b_1 )
        (free-loc_2_1 ))
    )


    (:action move_19
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_2_2 ) (at-b_0-loc_1_0 )) (at-b_1-loc_2_1 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (clear-b_1 )
        (free-loc_2_2 ))
    )


    (:action move_20
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_1_1 ) (at-b_1-loc_2_0 )) (at-b_0-loc_1_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (clear-b_0 )
        (free-loc_1_1 ))
    )


    (:action move_21
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_1_1 ) (at-b_1-loc_2_1 )) (at-b_0-loc_1_0 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (clear-b_0 )
        (free-loc_1_1 ))
    )


    (:action move_22
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_2_1 ) (at-b_1-loc_1_0 )) (at-b_0-loc_2_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (clear-b_0 )
        (free-loc_2_1 ))
    )


    (:action move_23
     :parameters ()
     :precondition (and (and (and (and (and (at-b_2-loc_2_2 ) (at-b_1-loc_1_0 )) (at-b_0-loc_2_1 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (clear-b_0 )
        (free-loc_2_2 ))
    )


    (:action move_24
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_1-loc_1_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_25
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_1-loc_2_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_26
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_1-loc_2_1 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_27
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_1_0 ) (at-b_1-loc_2_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_28
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_1_0 ) (at-b_1-loc_2_1 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_29
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_2_0 ) (at-b_1-loc_1_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_0-loc_2_0 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_30
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_2-loc_1_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_31
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_2-loc_2_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_32
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_0_0 ) (at-b_2-loc_2_1 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_33
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_1_0 ) (at-b_2-loc_2_0 )) (free-loc_2_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_0-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_34
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_1_0 ) (at-b_2-loc_2_1 )) (free-loc_2_2 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_0-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_35
     :parameters ()
     :precondition (and (and (and (and (at-b_0-loc_2_0 ) (at-b_2-loc_1_0 )) (free-loc_1_1 )) (clear-b_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_0-loc_2_0 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_0-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_36
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_0-loc_1_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_37
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_0-loc_2_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_38
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_0-loc_2_1 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_39
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_1_0 ) (at-b_0-loc_2_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_40
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_1_0 ) (at-b_0-loc_2_1 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_41
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_2_0 ) (at-b_0-loc_1_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_0 ))
     :effect (and
        (not (at-b_1-loc_2_0 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_42
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_2-loc_1_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_43
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_2-loc_2_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_44
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_0_0 ) (at-b_2-loc_2_1 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_45
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_1_0 ) (at-b_2-loc_2_0 )) (free-loc_2_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_1 ))
        (at-b_1-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_46
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_1_0 ) (at-b_2-loc_2_1 )) (free-loc_2_2 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (clear-b_2 ))
        (not (free-loc_2_2 ))
        (at-b_1-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_47
     :parameters ()
     :precondition (and (and (and (and (at-b_1-loc_2_0 ) (at-b_2-loc_1_0 )) (free-loc_1_1 )) (clear-b_1 )) (clear-b_2 ))
     :effect (and
        (not (at-b_1-loc_2_0 ))
        (not (clear-b_2 ))
        (not (free-loc_1_1 ))
        (at-b_1-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_48
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_0-loc_1_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_49
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_0-loc_2_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_50
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_0-loc_2_1 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_51
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_1_0 ) (at-b_0-loc_2_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_52
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_1_0 ) (at-b_0-loc_2_1 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (clear-b_0 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_53
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_2_0 ) (at-b_0-loc_1_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_0 ))
     :effect (and
        (not (at-b_2-loc_2_0 ))
        (not (clear-b_0 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_54
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_1-loc_1_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (free-loc_0_0 ))
    )


    (:action move_55
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_1-loc_2_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (free-loc_0_0 ))
    )


    (:action move_56
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_0_0 ) (at-b_1-loc_2_1 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (free-loc_0_0 ))
    )


    (:action move_57
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_1_0 ) (at-b_1-loc_2_0 )) (free-loc_2_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_1 ))
        (at-b_2-loc_2_1 )
        (free-loc_1_0 ))
    )


    (:action move_58
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_1_0 ) (at-b_1-loc_2_1 )) (free-loc_2_2 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (clear-b_1 ))
        (not (free-loc_2_2 ))
        (at-b_2-loc_2_2 )
        (free-loc_1_0 ))
    )


    (:action move_59
     :parameters ()
     :precondition (and (and (and (and (at-b_2-loc_2_0 ) (at-b_1-loc_1_0 )) (free-loc_1_1 )) (clear-b_2 )) (clear-b_1 ))
     :effect (and
        (not (at-b_2-loc_2_0 ))
        (not (clear-b_1 ))
        (not (free-loc_1_1 ))
        (at-b_2-loc_1_1 )
        (free-loc_2_0 ))
    )


    (:action move_60
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_1_1 ) (at-b_1-loc_1_0 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_1 ))
    )


    (:action move_61
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_1_1 ) (at-b_1-loc_1_0 )) (free-loc_2_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_0-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_1 ))
    )


    (:action move_62
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_1 ) (at-b_1-loc_2_0 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_1 ))
    )


    (:action move_63
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_1 ) (at-b_1-loc_2_0 )) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_1 ))
    )


    (:action move_64
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_2 ) (at-b_1-loc_2_1 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_1 ))
    )


    (:action move_65
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_2 ) (at-b_1-loc_2_1 )) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_1 ))
    )


    (:action move_66
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_1_1 ) (at-b_2-loc_1_0 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_2 ))
    )


    (:action move_67
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_1_1 ) (at-b_2-loc_1_0 )) (free-loc_2_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_0-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_2 ))
    )


    (:action move_68
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_1 ) (at-b_2-loc_2_0 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_2 ))
    )


    (:action move_69
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_1 ) (at-b_2-loc_2_0 )) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_2 ))
    )


    (:action move_70
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_2 ) (at-b_2-loc_2_1 )) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_2 ))
    )


    (:action move_71
     :parameters ()
     :precondition (and (and (and (at-b_0-loc_2_2 ) (at-b_2-loc_2_1 )) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_2 ))
    )


    (:action move_72
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_1_1 ) (at-b_0-loc_1_0 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_0 ))
    )


    (:action move_73
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_1_1 ) (at-b_0-loc_1_0 )) (free-loc_2_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_1-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_0 ))
    )


    (:action move_74
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_1 ) (at-b_0-loc_2_0 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_0 ))
    )


    (:action move_75
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_1 ) (at-b_0-loc_2_0 )) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_0 ))
    )


    (:action move_76
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_2 ) (at-b_0-loc_2_1 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_0 ))
    )


    (:action move_77
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_2 ) (at-b_0-loc_2_1 )) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_0 ))
    )


    (:action move_78
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_1_1 ) (at-b_2-loc_1_0 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_2 ))
    )


    (:action move_79
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_1_1 ) (at-b_2-loc_1_0 )) (free-loc_2_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_1-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_2 ))
    )


    (:action move_80
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_1 ) (at-b_2-loc_2_0 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_2 ))
    )


    (:action move_81
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_1 ) (at-b_2-loc_2_0 )) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_2 ))
    )


    (:action move_82
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_2 ) (at-b_2-loc_2_1 )) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_2 ))
    )


    (:action move_83
     :parameters ()
     :precondition (and (and (and (at-b_1-loc_2_2 ) (at-b_2-loc_2_1 )) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_2 ))
    )


    (:action move_84
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_1_1 ) (at-b_0-loc_1_0 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_0 ))
    )


    (:action move_85
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_1_1 ) (at-b_0-loc_1_0 )) (free-loc_2_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_2-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_0 ))
    )


    (:action move_86
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_1 ) (at-b_0-loc_2_0 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_0 ))
    )


    (:action move_87
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_1 ) (at-b_0-loc_2_0 )) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_0 ))
    )


    (:action move_88
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_2 ) (at-b_0-loc_2_1 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_0 ))
    )


    (:action move_89
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_2 ) (at-b_0-loc_2_1 )) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_0 ))
    )


    (:action move_90
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_1_1 ) (at-b_1-loc_1_0 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_1_1 )
        (clear-b_1 ))
    )


    (:action move_91
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_1_1 ) (at-b_1-loc_1_0 )) (free-loc_2_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_1 ))
        (not (free-loc_2_0 ))
        (at-b_2-loc_2_0 )
        (free-loc_1_1 )
        (clear-b_1 ))
    )


    (:action move_92
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_1 ) (at-b_1-loc_2_0 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_2_1 )
        (clear-b_1 ))
    )


    (:action move_93
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_1 ) (at-b_1-loc_2_0 )) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_1 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_2_1 )
        (clear-b_1 ))
    )


    (:action move_94
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_2 ) (at-b_1-loc_2_1 )) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_2_2 )
        (clear-b_1 ))
    )


    (:action move_95
     :parameters ()
     :precondition (and (and (and (at-b_2-loc_2_2 ) (at-b_1-loc_2_1 )) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_2 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_2_2 )
        (clear-b_1 ))
    )


    (:action move_96
     :parameters ()
     :precondition (and (and (at-b_0-loc_0_0 ) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_0_0 ))
    )


    (:action move_97
     :parameters ()
     :precondition (and (and (at-b_0-loc_0_0 ) (free-loc_2_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_0_0 ))
        (not (free-loc_2_0 ))
        (at-b_0-loc_2_0 )
        (free-loc_0_0 ))
    )


    (:action move_98
     :parameters ()
     :precondition (and (and (at-b_0-loc_1_0 ) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_1_0 ))
    )


    (:action move_99
     :parameters ()
     :precondition (and (and (at-b_0-loc_1_0 ) (free-loc_2_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_1_0 ))
        (not (free-loc_2_0 ))
        (at-b_0-loc_2_0 )
        (free-loc_1_0 ))
    )


    (:action move_100
     :parameters ()
     :precondition (and (and (at-b_0-loc_2_0 ) (free-loc_0_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_0 ))
        (not (free-loc_0_0 ))
        (at-b_0-loc_0_0 )
        (free-loc_2_0 ))
    )


    (:action move_101
     :parameters ()
     :precondition (and (and (at-b_0-loc_2_0 ) (free-loc_1_0 )) (clear-b_0 ))
     :effect (and
        (not (at-b_0-loc_2_0 ))
        (not (free-loc_1_0 ))
        (at-b_0-loc_1_0 )
        (free-loc_2_0 ))
    )


    (:action move_102
     :parameters ()
     :precondition (and (and (at-b_1-loc_0_0 ) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_0_0 ))
    )


    (:action move_103
     :parameters ()
     :precondition (and (and (at-b_1-loc_0_0 ) (free-loc_2_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_0_0 ))
        (not (free-loc_2_0 ))
        (at-b_1-loc_2_0 )
        (free-loc_0_0 ))
    )


    (:action move_104
     :parameters ()
     :precondition (and (and (at-b_1-loc_1_0 ) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_1_0 ))
    )


    (:action move_105
     :parameters ()
     :precondition (and (and (at-b_1-loc_1_0 ) (free-loc_2_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_1_0 ))
        (not (free-loc_2_0 ))
        (at-b_1-loc_2_0 )
        (free-loc_1_0 ))
    )


    (:action move_106
     :parameters ()
     :precondition (and (and (at-b_1-loc_2_0 ) (free-loc_0_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_0 ))
        (not (free-loc_0_0 ))
        (at-b_1-loc_0_0 )
        (free-loc_2_0 ))
    )


    (:action move_107
     :parameters ()
     :precondition (and (and (at-b_1-loc_2_0 ) (free-loc_1_0 )) (clear-b_1 ))
     :effect (and
        (not (at-b_1-loc_2_0 ))
        (not (free-loc_1_0 ))
        (at-b_1-loc_1_0 )
        (free-loc_2_0 ))
    )


    (:action move_108
     :parameters ()
     :precondition (and (and (at-b_2-loc_0_0 ) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_0_0 ))
    )


    (:action move_109
     :parameters ()
     :precondition (and (and (at-b_2-loc_0_0 ) (free-loc_2_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_0_0 ))
        (not (free-loc_2_0 ))
        (at-b_2-loc_2_0 )
        (free-loc_0_0 ))
    )


    (:action move_110
     :parameters ()
     :precondition (and (and (at-b_2-loc_1_0 ) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_1_0 ))
    )


    (:action move_111
     :parameters ()
     :precondition (and (and (at-b_2-loc_1_0 ) (free-loc_2_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_1_0 ))
        (not (free-loc_2_0 ))
        (at-b_2-loc_2_0 )
        (free-loc_1_0 ))
    )


    (:action move_112
     :parameters ()
     :precondition (and (and (at-b_2-loc_2_0 ) (free-loc_0_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_0 ))
        (not (free-loc_0_0 ))
        (at-b_2-loc_0_0 )
        (free-loc_2_0 ))
    )


    (:action move_113
     :parameters ()
     :precondition (and (and (at-b_2-loc_2_0 ) (free-loc_1_0 )) (clear-b_2 ))
     :effect (and
        (not (at-b_2-loc_2_0 ))
        (not (free-loc_1_0 ))
        (at-b_2-loc_1_0 )
        (free-loc_2_0 ))
    )

)