
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem TOLproblem176)
    (:domain TOL)

    (:objects
        
    )

    (:init
        (at-b_2-loc_0_0 )
        (clear-b_2 )
        (free-loc_0_1 )
        (free-loc_0_2 )
        (at-b_1-loc_1_0 )
        (clear-b_1 )
        (free-loc_1_1 )
        (at-b_0-loc_2_0 )
        (clear-b_0 )
        (handempty )
    )

    (:goal
        (and (at-b_1-loc_2_0 ) (and (at-b_2-loc_1_1 ) (at-b_0-loc_1_0 )))
    )

    
    
    
)

