
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain gridworld)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (at_0_0 )
        (at_0_1 )
        (at_0_2 )
        (at_0_3 )
        (at_0_4 )
        (at_0_5 )
        (at_0_6 )
        (at_0_7 )
        (at_0_8 )
        (at_0_9 )
        (at_1_0 )
        (at_1_1 )
        (at_1_2 )
        (at_1_3 )
        (at_1_4 )
        (at_1_5 )
        (at_1_6 )
        (at_1_7 )
        (at_1_8 )
        (at_1_9 )
        (at_2_0 )
        (at_2_1 )
        (at_2_2 )
        (at_2_3 )
        (at_2_4 )
        (at_2_5 )
        (at_2_6 )
        (at_2_7 )
        (at_2_8 )
        (at_2_9 )
        (at_3_0 )
        (at_3_1 )
        (at_3_2 )
        (at_3_3 )
        (at_3_4 )
        (at_3_5 )
        (at_3_6 )
        (at_3_7 )
        (at_3_8 )
        (at_3_9 )
        (at_4_0 )
        (at_4_1 )
        (at_4_2 )
        (at_4_3 )
        (at_4_4 )
        (at_4_5 )
        (at_4_6 )
        (at_4_7 )
        (at_4_8 )
        (at_4_9 )
        (at_5_0 )
        (at_5_1 )
        (at_5_2 )
        (at_5_3 )
        (at_5_4 )
        (at_5_5 )
        (at_5_6 )
        (at_5_7 )
        (at_5_8 )
        (at_5_9 )
        (at_6_0 )
        (at_6_1 )
        (at_6_2 )
        (at_6_3 )
        (at_6_4 )
        (at_6_5 )
        (at_6_6 )
        (at_6_7 )
        (at_6_8 )
        (at_6_9 )
        (at_7_0 )
        (at_7_1 )
        (at_7_2 )
        (at_7_3 )
        (at_7_4 )
        (at_7_5 )
        (at_7_6 )
        (at_7_7 )
        (at_7_8 )
        (at_7_9 )
        (at_8_0 )
        (at_8_1 )
        (at_8_2 )
        (at_8_3 )
        (at_8_4 )
        (at_8_5 )
        (at_8_6 )
        (at_8_7 )
        (at_8_8 )
        (at_8_9 )
        (at_9_0 )
        (at_9_1 )
        (at_9_2 )
        (at_9_3 )
        (at_9_4 )
        (at_9_5 )
        (at_9_6 )
        (at_9_7 )
        (at_9_8 )
        (at_9_9 )
        (visited_0_0 )
        (visited_0_1 )
        (visited_0_2 )
        (visited_0_3 )
        (visited_0_4 )
        (visited_0_5 )
        (visited_0_6 )
        (visited_0_7 )
        (visited_0_8 )
        (visited_0_9 )
        (visited_1_0 )
        (visited_1_1 )
        (visited_1_2 )
        (visited_1_3 )
        (visited_1_4 )
        (visited_1_5 )
        (visited_1_6 )
        (visited_1_7 )
        (visited_1_8 )
        (visited_1_9 )
        (visited_2_0 )
        (visited_2_1 )
        (visited_2_2 )
        (visited_2_3 )
        (visited_2_4 )
        (visited_2_5 )
        (visited_2_6 )
        (visited_2_7 )
        (visited_2_8 )
        (visited_2_9 )
        (visited_3_0 )
        (visited_3_1 )
        (visited_3_2 )
        (visited_3_3 )
        (visited_3_4 )
        (visited_3_5 )
        (visited_3_6 )
        (visited_3_7 )
        (visited_3_8 )
        (visited_3_9 )
        (visited_4_0 )
        (visited_4_1 )
        (visited_4_2 )
        (visited_4_3 )
        (visited_4_4 )
        (visited_4_5 )
        (visited_4_6 )
        (visited_4_7 )
        (visited_4_8 )
        (visited_4_9 )
        (visited_5_0 )
        (visited_5_1 )
        (visited_5_2 )
        (visited_5_3 )
        (visited_5_4 )
        (visited_5_5 )
        (visited_5_6 )
        (visited_5_7 )
        (visited_5_8 )
        (visited_5_9 )
        (visited_6_0 )
        (visited_6_1 )
        (visited_6_2 )
        (visited_6_3 )
        (visited_6_4 )
        (visited_6_5 )
        (visited_6_6 )
        (visited_6_7 )
        (visited_6_8 )
        (visited_6_9 )
        (visited_7_0 )
        (visited_7_1 )
        (visited_7_2 )
        (visited_7_3 )
        (visited_7_4 )
        (visited_7_5 )
        (visited_7_6 )
        (visited_7_7 )
        (visited_7_8 )
        (visited_7_9 )
        (visited_8_0 )
        (visited_8_1 )
        (visited_8_2 )
        (visited_8_3 )
        (visited_8_4 )
        (visited_8_5 )
        (visited_8_6 )
        (visited_8_7 )
        (visited_8_8 )
        (visited_8_9 )
        (visited_9_0 )
        (visited_9_1 )
        (visited_9_2 )
        (visited_9_3 )
        (visited_9_4 )
        (visited_9_5 )
        (visited_9_6 )
        (visited_9_7 )
        (visited_9_8 )
        (visited_9_9 )
        (connected_0_0_0_1 )
        (connected_0_1_0_0 )
        (connected_0_1_0_2 )
        (connected_0_2_0_1 )
        (connected_0_2_0_3 )
        (connected_0_3_0_2 )
        (connected_0_3_0_4 )
        (connected_0_4_0_3 )
        (connected_0_4_0_5 )
        (connected_0_5_0_4 )
        (connected_0_5_0_6 )
        (connected_0_6_0_5 )
        (connected_0_6_0_7 )
        (connected_0_7_0_6 )
        (connected_0_7_0_8 )
        (connected_0_8_0_7 )
        (connected_0_8_0_9 )
        (connected_0_9_0_8 )
        (connected_1_0_1_1 )
        (connected_1_1_1_0 )
        (connected_1_1_1_2 )
        (connected_1_2_1_1 )
        (connected_1_2_1_3 )
        (connected_1_3_1_2 )
        (connected_1_3_1_4 )
        (connected_1_4_1_3 )
        (connected_1_4_1_5 )
        (connected_1_5_1_4 )
        (connected_1_5_1_6 )
        (connected_1_6_1_5 )
        (connected_1_6_1_7 )
        (connected_1_7_1_6 )
        (connected_1_7_1_8 )
        (connected_1_8_1_7 )
        (connected_1_8_1_9 )
        (connected_1_9_1_8 )
        (connected_2_0_2_1 )
        (connected_2_1_2_0 )
        (connected_2_1_2_2 )
        (connected_2_2_2_1 )
        (connected_2_2_2_3 )
        (connected_2_3_2_2 )
        (connected_2_3_2_4 )
        (connected_2_4_2_3 )
        (connected_2_4_2_5 )
        (connected_2_5_2_4 )
        (connected_2_5_2_6 )
        (connected_2_6_2_5 )
        (connected_2_6_2_7 )
        (connected_2_7_2_6 )
        (connected_2_7_2_8 )
        (connected_2_8_2_7 )
        (connected_2_8_2_9 )
        (connected_2_9_2_8 )
        (connected_3_0_3_1 )
        (connected_3_1_3_0 )
        (connected_3_1_3_2 )
        (connected_3_2_3_1 )
        (connected_3_2_3_3 )
        (connected_3_3_3_2 )
        (connected_3_3_3_4 )
        (connected_3_4_3_3 )
        (connected_3_4_3_5 )
        (connected_3_5_3_4 )
        (connected_3_5_3_6 )
        (connected_3_6_3_5 )
        (connected_3_6_3_7 )
        (connected_3_7_3_6 )
        (connected_3_7_3_8 )
        (connected_3_8_3_7 )
        (connected_3_8_3_9 )
        (connected_3_9_3_8 )
        (connected_4_0_4_1 )
        (connected_4_1_4_0 )
        (connected_4_1_4_2 )
        (connected_4_2_4_1 )
        (connected_4_2_4_3 )
        (connected_4_3_4_2 )
        (connected_4_3_4_4 )
        (connected_4_4_4_3 )
        (connected_4_4_4_5 )
        (connected_4_5_4_4 )
        (connected_4_5_4_6 )
        (connected_4_6_4_5 )
        (connected_4_6_4_7 )
        (connected_4_7_4_6 )
        (connected_4_7_4_8 )
        (connected_4_8_4_7 )
        (connected_4_8_4_9 )
        (connected_4_9_4_8 )
        (connected_5_0_5_1 )
        (connected_5_1_5_0 )
        (connected_5_1_5_2 )
        (connected_5_2_5_1 )
        (connected_5_2_5_3 )
        (connected_5_3_5_2 )
        (connected_5_3_5_4 )
        (connected_5_4_5_3 )
        (connected_5_4_5_5 )
        (connected_5_5_5_4 )
        (connected_5_5_5_6 )
        (connected_5_6_5_5 )
        (connected_5_6_5_7 )
        (connected_5_7_5_6 )
        (connected_5_7_5_8 )
        (connected_5_8_5_7 )
        (connected_5_8_5_9 )
        (connected_5_9_5_8 )
        (connected_6_0_6_1 )
        (connected_6_1_6_0 )
        (connected_6_1_6_2 )
        (connected_6_2_6_1 )
        (connected_6_2_6_3 )
        (connected_6_3_6_2 )
        (connected_6_3_6_4 )
        (connected_6_4_6_3 )
        (connected_6_4_6_5 )
        (connected_6_5_6_4 )
        (connected_6_5_6_6 )
        (connected_6_6_6_5 )
        (connected_6_6_6_7 )
        (connected_6_7_6_6 )
        (connected_6_7_6_8 )
        (connected_6_8_6_7 )
        (connected_6_8_6_9 )
        (connected_6_9_6_8 )
        (connected_7_0_7_1 )
        (connected_7_1_7_0 )
        (connected_7_1_7_2 )
        (connected_7_2_7_1 )
        (connected_7_2_7_3 )
        (connected_7_3_7_2 )
        (connected_7_3_7_4 )
        (connected_7_4_7_3 )
        (connected_7_4_7_5 )
        (connected_7_5_7_4 )
        (connected_7_5_7_6 )
        (connected_7_6_7_5 )
        (connected_7_6_7_7 )
        (connected_7_7_7_6 )
        (connected_7_7_7_8 )
        (connected_7_8_7_7 )
        (connected_7_8_7_9 )
        (connected_7_9_7_8 )
        (connected_8_0_8_1 )
        (connected_8_1_8_0 )
        (connected_8_1_8_2 )
        (connected_8_2_8_1 )
        (connected_8_2_8_3 )
        (connected_8_3_8_2 )
        (connected_8_3_8_4 )
        (connected_8_4_8_3 )
        (connected_8_4_8_5 )
        (connected_8_5_8_4 )
        (connected_8_5_8_6 )
        (connected_8_6_8_5 )
        (connected_8_6_8_7 )
        (connected_8_7_8_6 )
        (connected_8_7_8_8 )
        (connected_8_8_8_7 )
        (connected_8_8_8_9 )
        (connected_8_9_8_8 )
        (connected_9_0_9_1 )
        (connected_9_1_9_0 )
        (connected_9_1_9_2 )
        (connected_9_2_9_1 )
        (connected_9_2_9_3 )
        (connected_9_3_9_2 )
        (connected_9_3_9_4 )
        (connected_9_4_9_3 )
        (connected_9_4_9_5 )
        (connected_9_5_9_4 )
        (connected_9_5_9_6 )
        (connected_9_6_9_5 )
        (connected_9_6_9_7 )
        (connected_9_7_9_6 )
        (connected_9_7_9_8 )
        (connected_9_8_9_7 )
        (connected_9_8_9_9 )
        (connected_9_9_9_8 )
        (connected_0_0_1_0 )
        (connected_1_0_0_0 )
        (connected_0_1_1_1 )
        (connected_1_1_0_1 )
        (connected_0_2_1_2 )
        (connected_1_2_0_2 )
        (connected_0_3_1_3 )
        (connected_1_3_0_3 )
        (connected_0_4_1_4 )
        (connected_1_4_0_4 )
        (connected_0_5_1_5 )
        (connected_1_5_0_5 )
        (connected_0_6_1_6 )
        (connected_1_6_0_6 )
        (connected_0_7_1_7 )
        (connected_1_7_0_7 )
        (connected_0_8_1_8 )
        (connected_1_8_0_8 )
        (connected_0_9_1_9 )
        (connected_1_9_0_9 )
        (connected_1_0_2_0 )
        (connected_2_0_1_0 )
        (connected_1_1_2_1 )
        (connected_2_1_1_1 )
        (connected_1_2_2_2 )
        (connected_2_2_1_2 )
        (connected_1_3_2_3 )
        (connected_2_3_1_3 )
        (connected_1_4_2_4 )
        (connected_2_4_1_4 )
        (connected_1_5_2_5 )
        (connected_2_5_1_5 )
        (connected_1_6_2_6 )
        (connected_2_6_1_6 )
        (connected_1_7_2_7 )
        (connected_2_7_1_7 )
        (connected_1_8_2_8 )
        (connected_2_8_1_8 )
        (connected_1_9_2_9 )
        (connected_2_9_1_9 )
        (connected_2_0_3_0 )
        (connected_3_0_2_0 )
        (connected_2_1_3_1 )
        (connected_3_1_2_1 )
        (connected_2_2_3_2 )
        (connected_3_2_2_2 )
        (connected_2_3_3_3 )
        (connected_3_3_2_3 )
        (connected_2_4_3_4 )
        (connected_3_4_2_4 )
        (connected_2_5_3_5 )
        (connected_3_5_2_5 )
        (connected_2_6_3_6 )
        (connected_3_6_2_6 )
        (connected_2_7_3_7 )
        (connected_3_7_2_7 )
        (connected_2_8_3_8 )
        (connected_3_8_2_8 )
        (connected_2_9_3_9 )
        (connected_3_9_2_9 )
        (connected_3_0_4_0 )
        (connected_4_0_3_0 )
        (connected_3_1_4_1 )
        (connected_4_1_3_1 )
        (connected_3_2_4_2 )
        (connected_4_2_3_2 )
        (connected_3_3_4_3 )
        (connected_4_3_3_3 )
        (connected_3_4_4_4 )
        (connected_4_4_3_4 )
        (connected_3_5_4_5 )
        (connected_4_5_3_5 )
        (connected_3_6_4_6 )
        (connected_4_6_3_6 )
        (connected_3_7_4_7 )
        (connected_4_7_3_7 )
        (connected_3_8_4_8 )
        (connected_4_8_3_8 )
        (connected_3_9_4_9 )
        (connected_4_9_3_9 )
        (connected_4_0_5_0 )
        (connected_5_0_4_0 )
        (connected_4_1_5_1 )
        (connected_5_1_4_1 )
        (connected_4_2_5_2 )
        (connected_5_2_4_2 )
        (connected_4_3_5_3 )
        (connected_5_3_4_3 )
        (connected_4_4_5_4 )
        (connected_5_4_4_4 )
        (connected_4_5_5_5 )
        (connected_5_5_4_5 )
        (connected_4_6_5_6 )
        (connected_5_6_4_6 )
        (connected_4_7_5_7 )
        (connected_5_7_4_7 )
        (connected_4_8_5_8 )
        (connected_5_8_4_8 )
        (connected_4_9_5_9 )
        (connected_5_9_4_9 )
        (connected_5_0_6_0 )
        (connected_6_0_5_0 )
        (connected_5_1_6_1 )
        (connected_6_1_5_1 )
        (connected_5_2_6_2 )
        (connected_6_2_5_2 )
        (connected_5_3_6_3 )
        (connected_6_3_5_3 )
        (connected_5_4_6_4 )
        (connected_6_4_5_4 )
        (connected_5_5_6_5 )
        (connected_6_5_5_5 )
        (connected_5_6_6_6 )
        (connected_6_6_5_6 )
        (connected_5_7_6_7 )
        (connected_6_7_5_7 )
        (connected_5_8_6_8 )
        (connected_6_8_5_8 )
        (connected_5_9_6_9 )
        (connected_6_9_5_9 )
        (connected_6_0_7_0 )
        (connected_7_0_6_0 )
        (connected_6_1_7_1 )
        (connected_7_1_6_1 )
        (connected_6_2_7_2 )
        (connected_7_2_6_2 )
        (connected_6_3_7_3 )
        (connected_7_3_6_3 )
        (connected_6_4_7_4 )
        (connected_7_4_6_4 )
        (connected_6_5_7_5 )
        (connected_7_5_6_5 )
        (connected_6_6_7_6 )
        (connected_7_6_6_6 )
        (connected_6_7_7_7 )
        (connected_7_7_6_7 )
        (connected_6_8_7_8 )
        (connected_7_8_6_8 )
        (connected_6_9_7_9 )
        (connected_7_9_6_9 )
        (connected_7_0_8_0 )
        (connected_8_0_7_0 )
        (connected_7_1_8_1 )
        (connected_8_1_7_1 )
        (connected_7_2_8_2 )
        (connected_8_2_7_2 )
        (connected_7_3_8_3 )
        (connected_8_3_7_3 )
        (connected_7_4_8_4 )
        (connected_8_4_7_4 )
        (connected_7_5_8_5 )
        (connected_8_5_7_5 )
        (connected_7_6_8_6 )
        (connected_8_6_7_6 )
        (connected_7_7_8_7 )
        (connected_8_7_7_7 )
        (connected_7_8_8_8 )
        (connected_8_8_7_8 )
        (connected_7_9_8_9 )
        (connected_8_9_7_9 )
        (connected_8_0_9_0 )
        (connected_9_0_8_0 )
        (connected_8_1_9_1 )
        (connected_9_1_8_1 )
        (connected_8_2_9_2 )
        (connected_9_2_8_2 )
        (connected_8_3_9_3 )
        (connected_9_3_8_3 )
        (connected_8_4_9_4 )
        (connected_9_4_8_4 )
        (connected_8_5_9_5 )
        (connected_9_5_8_5 )
        (connected_8_6_9_6 )
        (connected_9_6_8_6 )
        (connected_8_7_9_7 )
        (connected_9_7_8_7 )
        (connected_8_8_9_8 )
        (connected_9_8_8_8 )
        (connected_8_9_9_9 )
        (connected_9_9_8_9 )
    )

    (:functions
        
    )

    

    
    (:action move_0_0_0_1
     :parameters ()
     :precondition (and (at_0_0 ) (connected_0_0_0_1 ))
     :effect (and
        (not (at_0_0 ))
        (at_0_1 )
        (visited_0_1 ))
    )


    (:action move_0_1_0_0
     :parameters ()
     :precondition (and (at_0_1 ) (connected_0_1_0_0 ))
     :effect (and
        (not (at_0_1 ))
        (at_0_0 )
        (visited_0_0 ))
    )


    (:action move_0_1_0_2
     :parameters ()
     :precondition (and (at_0_1 ) (connected_0_1_0_2 ))
     :effect (and
        (not (at_0_1 ))
        (at_0_2 )
        (visited_0_2 ))
    )


    (:action move_0_2_0_1
     :parameters ()
     :precondition (and (at_0_2 ) (connected_0_2_0_1 ))
     :effect (and
        (not (at_0_2 ))
        (at_0_1 )
        (visited_0_1 ))
    )


    (:action move_0_2_0_3
     :parameters ()
     :precondition (and (at_0_2 ) (connected_0_2_0_3 ))
     :effect (and
        (not (at_0_2 ))
        (at_0_3 )
        (visited_0_3 ))
    )


    (:action move_0_3_0_2
     :parameters ()
     :precondition (and (at_0_3 ) (connected_0_3_0_2 ))
     :effect (and
        (not (at_0_3 ))
        (at_0_2 )
        (visited_0_2 ))
    )


    (:action move_0_3_0_4
     :parameters ()
     :precondition (and (at_0_3 ) (connected_0_3_0_4 ))
     :effect (and
        (not (at_0_3 ))
        (at_0_4 )
        (visited_0_4 ))
    )


    (:action move_0_4_0_3
     :parameters ()
     :precondition (and (at_0_4 ) (connected_0_4_0_3 ))
     :effect (and
        (not (at_0_4 ))
        (at_0_3 )
        (visited_0_3 ))
    )


    (:action move_0_4_0_5
     :parameters ()
     :precondition (and (at_0_4 ) (connected_0_4_0_5 ))
     :effect (and
        (not (at_0_4 ))
        (at_0_5 )
        (visited_0_5 ))
    )


    (:action move_0_5_0_4
     :parameters ()
     :precondition (and (at_0_5 ) (connected_0_5_0_4 ))
     :effect (and
        (not (at_0_5 ))
        (at_0_4 )
        (visited_0_4 ))
    )


    (:action move_0_5_0_6
     :parameters ()
     :precondition (and (at_0_5 ) (connected_0_5_0_6 ))
     :effect (and
        (not (at_0_5 ))
        (at_0_6 )
        (visited_0_6 ))
    )


    (:action move_0_6_0_5
     :parameters ()
     :precondition (and (at_0_6 ) (connected_0_6_0_5 ))
     :effect (and
        (not (at_0_6 ))
        (at_0_5 )
        (visited_0_5 ))
    )


    (:action move_0_6_0_7
     :parameters ()
     :precondition (and (at_0_6 ) (connected_0_6_0_7 ))
     :effect (and
        (not (at_0_6 ))
        (at_0_7 )
        (visited_0_7 ))
    )


    (:action move_0_7_0_6
     :parameters ()
     :precondition (and (at_0_7 ) (connected_0_7_0_6 ))
     :effect (and
        (not (at_0_7 ))
        (at_0_6 )
        (visited_0_6 ))
    )


    (:action move_0_7_0_8
     :parameters ()
     :precondition (and (at_0_7 ) (connected_0_7_0_8 ))
     :effect (and
        (not (at_0_7 ))
        (at_0_8 )
        (visited_0_8 ))
    )


    (:action move_0_8_0_7
     :parameters ()
     :precondition (and (at_0_8 ) (connected_0_8_0_7 ))
     :effect (and
        (not (at_0_8 ))
        (at_0_7 )
        (visited_0_7 ))
    )


    (:action move_0_8_0_9
     :parameters ()
     :precondition (and (at_0_8 ) (connected_0_8_0_9 ))
     :effect (and
        (not (at_0_8 ))
        (at_0_9 )
        (visited_0_9 ))
    )


    (:action move_0_9_0_8
     :parameters ()
     :precondition (and (at_0_9 ) (connected_0_9_0_8 ))
     :effect (and
        (not (at_0_9 ))
        (at_0_8 )
        (visited_0_8 ))
    )


    (:action move_1_0_1_1
     :parameters ()
     :precondition (and (at_1_0 ) (connected_1_0_1_1 ))
     :effect (and
        (not (at_1_0 ))
        (at_1_1 )
        (visited_1_1 ))
    )


    (:action move_1_1_1_0
     :parameters ()
     :precondition (and (at_1_1 ) (connected_1_1_1_0 ))
     :effect (and
        (not (at_1_1 ))
        (at_1_0 )
        (visited_1_0 ))
    )


    (:action move_1_1_1_2
     :parameters ()
     :precondition (and (at_1_1 ) (connected_1_1_1_2 ))
     :effect (and
        (not (at_1_1 ))
        (at_1_2 )
        (visited_1_2 ))
    )


    (:action move_1_2_1_1
     :parameters ()
     :precondition (and (at_1_2 ) (connected_1_2_1_1 ))
     :effect (and
        (not (at_1_2 ))
        (at_1_1 )
        (visited_1_1 ))
    )


    (:action move_1_2_1_3
     :parameters ()
     :precondition (and (at_1_2 ) (connected_1_2_1_3 ))
     :effect (and
        (not (at_1_2 ))
        (at_1_3 )
        (visited_1_3 ))
    )


    (:action move_1_3_1_2
     :parameters ()
     :precondition (and (at_1_3 ) (connected_1_3_1_2 ))
     :effect (and
        (not (at_1_3 ))
        (at_1_2 )
        (visited_1_2 ))
    )


    (:action move_1_3_1_4
     :parameters ()
     :precondition (and (at_1_3 ) (connected_1_3_1_4 ))
     :effect (and
        (not (at_1_3 ))
        (at_1_4 )
        (visited_1_4 ))
    )


    (:action move_1_4_1_3
     :parameters ()
     :precondition (and (at_1_4 ) (connected_1_4_1_3 ))
     :effect (and
        (not (at_1_4 ))
        (at_1_3 )
        (visited_1_3 ))
    )


    (:action move_1_4_1_5
     :parameters ()
     :precondition (and (at_1_4 ) (connected_1_4_1_5 ))
     :effect (and
        (not (at_1_4 ))
        (at_1_5 )
        (visited_1_5 ))
    )


    (:action move_1_5_1_4
     :parameters ()
     :precondition (and (at_1_5 ) (connected_1_5_1_4 ))
     :effect (and
        (not (at_1_5 ))
        (at_1_4 )
        (visited_1_4 ))
    )


    (:action move_1_5_1_6
     :parameters ()
     :precondition (and (at_1_5 ) (connected_1_5_1_6 ))
     :effect (and
        (not (at_1_5 ))
        (at_1_6 )
        (visited_1_6 ))
    )


    (:action move_1_6_1_5
     :parameters ()
     :precondition (and (at_1_6 ) (connected_1_6_1_5 ))
     :effect (and
        (not (at_1_6 ))
        (at_1_5 )
        (visited_1_5 ))
    )


    (:action move_1_6_1_7
     :parameters ()
     :precondition (and (at_1_6 ) (connected_1_6_1_7 ))
     :effect (and
        (not (at_1_6 ))
        (at_1_7 )
        (visited_1_7 ))
    )


    (:action move_1_7_1_6
     :parameters ()
     :precondition (and (at_1_7 ) (connected_1_7_1_6 ))
     :effect (and
        (not (at_1_7 ))
        (at_1_6 )
        (visited_1_6 ))
    )


    (:action move_1_7_1_8
     :parameters ()
     :precondition (and (at_1_7 ) (connected_1_7_1_8 ))
     :effect (and
        (not (at_1_7 ))
        (at_1_8 )
        (visited_1_8 ))
    )


    (:action move_1_8_1_7
     :parameters ()
     :precondition (and (at_1_8 ) (connected_1_8_1_7 ))
     :effect (and
        (not (at_1_8 ))
        (at_1_7 )
        (visited_1_7 ))
    )


    (:action move_1_8_1_9
     :parameters ()
     :precondition (and (at_1_8 ) (connected_1_8_1_9 ))
     :effect (and
        (not (at_1_8 ))
        (at_1_9 )
        (visited_1_9 ))
    )


    (:action move_1_9_1_8
     :parameters ()
     :precondition (and (at_1_9 ) (connected_1_9_1_8 ))
     :effect (and
        (not (at_1_9 ))
        (at_1_8 )
        (visited_1_8 ))
    )


    (:action move_2_0_2_1
     :parameters ()
     :precondition (and (at_2_0 ) (connected_2_0_2_1 ))
     :effect (and
        (not (at_2_0 ))
        (at_2_1 )
        (visited_2_1 ))
    )


    (:action move_2_1_2_0
     :parameters ()
     :precondition (and (at_2_1 ) (connected_2_1_2_0 ))
     :effect (and
        (not (at_2_1 ))
        (at_2_0 )
        (visited_2_0 ))
    )


    (:action move_2_1_2_2
     :parameters ()
     :precondition (and (at_2_1 ) (connected_2_1_2_2 ))
     :effect (and
        (not (at_2_1 ))
        (at_2_2 )
        (visited_2_2 ))
    )


    (:action move_2_2_2_1
     :parameters ()
     :precondition (and (at_2_2 ) (connected_2_2_2_1 ))
     :effect (and
        (not (at_2_2 ))
        (at_2_1 )
        (visited_2_1 ))
    )


    (:action move_2_2_2_3
     :parameters ()
     :precondition (and (at_2_2 ) (connected_2_2_2_3 ))
     :effect (and
        (not (at_2_2 ))
        (at_2_3 )
        (visited_2_3 ))
    )


    (:action move_2_3_2_2
     :parameters ()
     :precondition (and (at_2_3 ) (connected_2_3_2_2 ))
     :effect (and
        (not (at_2_3 ))
        (at_2_2 )
        (visited_2_2 ))
    )


    (:action move_2_3_2_4
     :parameters ()
     :precondition (and (at_2_3 ) (connected_2_3_2_4 ))
     :effect (and
        (not (at_2_3 ))
        (at_2_4 )
        (visited_2_4 ))
    )


    (:action move_2_4_2_3
     :parameters ()
     :precondition (and (at_2_4 ) (connected_2_4_2_3 ))
     :effect (and
        (not (at_2_4 ))
        (at_2_3 )
        (visited_2_3 ))
    )


    (:action move_2_4_2_5
     :parameters ()
     :precondition (and (at_2_4 ) (connected_2_4_2_5 ))
     :effect (and
        (not (at_2_4 ))
        (at_2_5 )
        (visited_2_5 ))
    )


    (:action move_2_5_2_4
     :parameters ()
     :precondition (and (at_2_5 ) (connected_2_5_2_4 ))
     :effect (and
        (not (at_2_5 ))
        (at_2_4 )
        (visited_2_4 ))
    )


    (:action move_2_5_2_6
     :parameters ()
     :precondition (and (at_2_5 ) (connected_2_5_2_6 ))
     :effect (and
        (not (at_2_5 ))
        (at_2_6 )
        (visited_2_6 ))
    )


    (:action move_2_6_2_5
     :parameters ()
     :precondition (and (at_2_6 ) (connected_2_6_2_5 ))
     :effect (and
        (not (at_2_6 ))
        (at_2_5 )
        (visited_2_5 ))
    )


    (:action move_2_6_2_7
     :parameters ()
     :precondition (and (at_2_6 ) (connected_2_6_2_7 ))
     :effect (and
        (not (at_2_6 ))
        (at_2_7 )
        (visited_2_7 ))
    )


    (:action move_2_7_2_6
     :parameters ()
     :precondition (and (at_2_7 ) (connected_2_7_2_6 ))
     :effect (and
        (not (at_2_7 ))
        (at_2_6 )
        (visited_2_6 ))
    )


    (:action move_2_7_2_8
     :parameters ()
     :precondition (and (at_2_7 ) (connected_2_7_2_8 ))
     :effect (and
        (not (at_2_7 ))
        (at_2_8 )
        (visited_2_8 ))
    )


    (:action move_2_8_2_7
     :parameters ()
     :precondition (and (at_2_8 ) (connected_2_8_2_7 ))
     :effect (and
        (not (at_2_8 ))
        (at_2_7 )
        (visited_2_7 ))
    )


    (:action move_2_8_2_9
     :parameters ()
     :precondition (and (at_2_8 ) (connected_2_8_2_9 ))
     :effect (and
        (not (at_2_8 ))
        (at_2_9 )
        (visited_2_9 ))
    )


    (:action move_2_9_2_8
     :parameters ()
     :precondition (and (at_2_9 ) (connected_2_9_2_8 ))
     :effect (and
        (not (at_2_9 ))
        (at_2_8 )
        (visited_2_8 ))
    )


    (:action move_3_0_3_1
     :parameters ()
     :precondition (and (at_3_0 ) (connected_3_0_3_1 ))
     :effect (and
        (not (at_3_0 ))
        (at_3_1 )
        (visited_3_1 ))
    )


    (:action move_3_1_3_0
     :parameters ()
     :precondition (and (at_3_1 ) (connected_3_1_3_0 ))
     :effect (and
        (not (at_3_1 ))
        (at_3_0 )
        (visited_3_0 ))
    )


    (:action move_3_1_3_2
     :parameters ()
     :precondition (and (at_3_1 ) (connected_3_1_3_2 ))
     :effect (and
        (not (at_3_1 ))
        (at_3_2 )
        (visited_3_2 ))
    )


    (:action move_3_2_3_1
     :parameters ()
     :precondition (and (at_3_2 ) (connected_3_2_3_1 ))
     :effect (and
        (not (at_3_2 ))
        (at_3_1 )
        (visited_3_1 ))
    )


    (:action move_3_2_3_3
     :parameters ()
     :precondition (and (at_3_2 ) (connected_3_2_3_3 ))
     :effect (and
        (not (at_3_2 ))
        (at_3_3 )
        (visited_3_3 ))
    )


    (:action move_3_3_3_2
     :parameters ()
     :precondition (and (at_3_3 ) (connected_3_3_3_2 ))
     :effect (and
        (not (at_3_3 ))
        (at_3_2 )
        (visited_3_2 ))
    )


    (:action move_3_3_3_4
     :parameters ()
     :precondition (and (at_3_3 ) (connected_3_3_3_4 ))
     :effect (and
        (not (at_3_3 ))
        (at_3_4 )
        (visited_3_4 ))
    )


    (:action move_3_4_3_3
     :parameters ()
     :precondition (and (at_3_4 ) (connected_3_4_3_3 ))
     :effect (and
        (not (at_3_4 ))
        (at_3_3 )
        (visited_3_3 ))
    )


    (:action move_3_4_3_5
     :parameters ()
     :precondition (and (at_3_4 ) (connected_3_4_3_5 ))
     :effect (and
        (not (at_3_4 ))
        (at_3_5 )
        (visited_3_5 ))
    )


    (:action move_3_5_3_4
     :parameters ()
     :precondition (and (at_3_5 ) (connected_3_5_3_4 ))
     :effect (and
        (not (at_3_5 ))
        (at_3_4 )
        (visited_3_4 ))
    )


    (:action move_3_5_3_6
     :parameters ()
     :precondition (and (at_3_5 ) (connected_3_5_3_6 ))
     :effect (and
        (not (at_3_5 ))
        (at_3_6 )
        (visited_3_6 ))
    )


    (:action move_3_6_3_5
     :parameters ()
     :precondition (and (at_3_6 ) (connected_3_6_3_5 ))
     :effect (and
        (not (at_3_6 ))
        (at_3_5 )
        (visited_3_5 ))
    )


    (:action move_3_6_3_7
     :parameters ()
     :precondition (and (at_3_6 ) (connected_3_6_3_7 ))
     :effect (and
        (not (at_3_6 ))
        (at_3_7 )
        (visited_3_7 ))
    )


    (:action move_3_7_3_6
     :parameters ()
     :precondition (and (at_3_7 ) (connected_3_7_3_6 ))
     :effect (and
        (not (at_3_7 ))
        (at_3_6 )
        (visited_3_6 ))
    )


    (:action move_3_7_3_8
     :parameters ()
     :precondition (and (at_3_7 ) (connected_3_7_3_8 ))
     :effect (and
        (not (at_3_7 ))
        (at_3_8 )
        (visited_3_8 ))
    )


    (:action move_3_8_3_7
     :parameters ()
     :precondition (and (at_3_8 ) (connected_3_8_3_7 ))
     :effect (and
        (not (at_3_8 ))
        (at_3_7 )
        (visited_3_7 ))
    )


    (:action move_3_8_3_9
     :parameters ()
     :precondition (and (at_3_8 ) (connected_3_8_3_9 ))
     :effect (and
        (not (at_3_8 ))
        (at_3_9 )
        (visited_3_9 ))
    )


    (:action move_3_9_3_8
     :parameters ()
     :precondition (and (at_3_9 ) (connected_3_9_3_8 ))
     :effect (and
        (not (at_3_9 ))
        (at_3_8 )
        (visited_3_8 ))
    )


    (:action move_4_0_4_1
     :parameters ()
     :precondition (and (at_4_0 ) (connected_4_0_4_1 ))
     :effect (and
        (not (at_4_0 ))
        (at_4_1 )
        (visited_4_1 ))
    )


    (:action move_4_1_4_0
     :parameters ()
     :precondition (and (at_4_1 ) (connected_4_1_4_0 ))
     :effect (and
        (not (at_4_1 ))
        (at_4_0 )
        (visited_4_0 ))
    )


    (:action move_4_1_4_2
     :parameters ()
     :precondition (and (at_4_1 ) (connected_4_1_4_2 ))
     :effect (and
        (not (at_4_1 ))
        (at_4_2 )
        (visited_4_2 ))
    )


    (:action move_4_2_4_1
     :parameters ()
     :precondition (and (at_4_2 ) (connected_4_2_4_1 ))
     :effect (and
        (not (at_4_2 ))
        (at_4_1 )
        (visited_4_1 ))
    )


    (:action move_4_2_4_3
     :parameters ()
     :precondition (and (at_4_2 ) (connected_4_2_4_3 ))
     :effect (and
        (not (at_4_2 ))
        (at_4_3 )
        (visited_4_3 ))
    )


    (:action move_4_3_4_2
     :parameters ()
     :precondition (and (at_4_3 ) (connected_4_3_4_2 ))
     :effect (and
        (not (at_4_3 ))
        (at_4_2 )
        (visited_4_2 ))
    )


    (:action move_4_3_4_4
     :parameters ()
     :precondition (and (at_4_3 ) (connected_4_3_4_4 ))
     :effect (and
        (not (at_4_3 ))
        (at_4_4 )
        (visited_4_4 ))
    )


    (:action move_4_4_4_3
     :parameters ()
     :precondition (and (at_4_4 ) (connected_4_4_4_3 ))
     :effect (and
        (not (at_4_4 ))
        (at_4_3 )
        (visited_4_3 ))
    )


    (:action move_4_4_4_5
     :parameters ()
     :precondition (and (at_4_4 ) (connected_4_4_4_5 ))
     :effect (and
        (not (at_4_4 ))
        (at_4_5 )
        (visited_4_5 ))
    )


    (:action move_4_5_4_4
     :parameters ()
     :precondition (and (at_4_5 ) (connected_4_5_4_4 ))
     :effect (and
        (not (at_4_5 ))
        (at_4_4 )
        (visited_4_4 ))
    )


    (:action move_4_5_4_6
     :parameters ()
     :precondition (and (at_4_5 ) (connected_4_5_4_6 ))
     :effect (and
        (not (at_4_5 ))
        (at_4_6 )
        (visited_4_6 ))
    )


    (:action move_4_6_4_5
     :parameters ()
     :precondition (and (at_4_6 ) (connected_4_6_4_5 ))
     :effect (and
        (not (at_4_6 ))
        (at_4_5 )
        (visited_4_5 ))
    )


    (:action move_4_6_4_7
     :parameters ()
     :precondition (and (at_4_6 ) (connected_4_6_4_7 ))
     :effect (and
        (not (at_4_6 ))
        (at_4_7 )
        (visited_4_7 ))
    )


    (:action move_4_7_4_6
     :parameters ()
     :precondition (and (at_4_7 ) (connected_4_7_4_6 ))
     :effect (and
        (not (at_4_7 ))
        (at_4_6 )
        (visited_4_6 ))
    )


    (:action move_4_7_4_8
     :parameters ()
     :precondition (and (at_4_7 ) (connected_4_7_4_8 ))
     :effect (and
        (not (at_4_7 ))
        (at_4_8 )
        (visited_4_8 ))
    )


    (:action move_4_8_4_7
     :parameters ()
     :precondition (and (at_4_8 ) (connected_4_8_4_7 ))
     :effect (and
        (not (at_4_8 ))
        (at_4_7 )
        (visited_4_7 ))
    )


    (:action move_4_8_4_9
     :parameters ()
     :precondition (and (at_4_8 ) (connected_4_8_4_9 ))
     :effect (and
        (not (at_4_8 ))
        (at_4_9 )
        (visited_4_9 ))
    )


    (:action move_4_9_4_8
     :parameters ()
     :precondition (and (at_4_9 ) (connected_4_9_4_8 ))
     :effect (and
        (not (at_4_9 ))
        (at_4_8 )
        (visited_4_8 ))
    )


    (:action move_5_0_5_1
     :parameters ()
     :precondition (and (at_5_0 ) (connected_5_0_5_1 ))
     :effect (and
        (not (at_5_0 ))
        (at_5_1 )
        (visited_5_1 ))
    )


    (:action move_5_1_5_0
     :parameters ()
     :precondition (and (at_5_1 ) (connected_5_1_5_0 ))
     :effect (and
        (not (at_5_1 ))
        (at_5_0 )
        (visited_5_0 ))
    )


    (:action move_5_1_5_2
     :parameters ()
     :precondition (and (at_5_1 ) (connected_5_1_5_2 ))
     :effect (and
        (not (at_5_1 ))
        (at_5_2 )
        (visited_5_2 ))
    )


    (:action move_5_2_5_1
     :parameters ()
     :precondition (and (at_5_2 ) (connected_5_2_5_1 ))
     :effect (and
        (not (at_5_2 ))
        (at_5_1 )
        (visited_5_1 ))
    )


    (:action move_5_2_5_3
     :parameters ()
     :precondition (and (at_5_2 ) (connected_5_2_5_3 ))
     :effect (and
        (not (at_5_2 ))
        (at_5_3 )
        (visited_5_3 ))
    )


    (:action move_5_3_5_2
     :parameters ()
     :precondition (and (at_5_3 ) (connected_5_3_5_2 ))
     :effect (and
        (not (at_5_3 ))
        (at_5_2 )
        (visited_5_2 ))
    )


    (:action move_5_3_5_4
     :parameters ()
     :precondition (and (at_5_3 ) (connected_5_3_5_4 ))
     :effect (and
        (not (at_5_3 ))
        (at_5_4 )
        (visited_5_4 ))
    )


    (:action move_5_4_5_3
     :parameters ()
     :precondition (and (at_5_4 ) (connected_5_4_5_3 ))
     :effect (and
        (not (at_5_4 ))
        (at_5_3 )
        (visited_5_3 ))
    )


    (:action move_5_4_5_5
     :parameters ()
     :precondition (and (at_5_4 ) (connected_5_4_5_5 ))
     :effect (and
        (not (at_5_4 ))
        (at_5_5 )
        (visited_5_5 ))
    )


    (:action move_5_5_5_4
     :parameters ()
     :precondition (and (at_5_5 ) (connected_5_5_5_4 ))
     :effect (and
        (not (at_5_5 ))
        (at_5_4 )
        (visited_5_4 ))
    )


    (:action move_5_5_5_6
     :parameters ()
     :precondition (and (at_5_5 ) (connected_5_5_5_6 ))
     :effect (and
        (not (at_5_5 ))
        (at_5_6 )
        (visited_5_6 ))
    )


    (:action move_5_6_5_5
     :parameters ()
     :precondition (and (at_5_6 ) (connected_5_6_5_5 ))
     :effect (and
        (not (at_5_6 ))
        (at_5_5 )
        (visited_5_5 ))
    )


    (:action move_5_6_5_7
     :parameters ()
     :precondition (and (at_5_6 ) (connected_5_6_5_7 ))
     :effect (and
        (not (at_5_6 ))
        (at_5_7 )
        (visited_5_7 ))
    )


    (:action move_5_7_5_6
     :parameters ()
     :precondition (and (at_5_7 ) (connected_5_7_5_6 ))
     :effect (and
        (not (at_5_7 ))
        (at_5_6 )
        (visited_5_6 ))
    )


    (:action move_5_7_5_8
     :parameters ()
     :precondition (and (at_5_7 ) (connected_5_7_5_8 ))
     :effect (and
        (not (at_5_7 ))
        (at_5_8 )
        (visited_5_8 ))
    )


    (:action move_5_8_5_7
     :parameters ()
     :precondition (and (at_5_8 ) (connected_5_8_5_7 ))
     :effect (and
        (not (at_5_8 ))
        (at_5_7 )
        (visited_5_7 ))
    )


    (:action move_5_8_5_9
     :parameters ()
     :precondition (and (at_5_8 ) (connected_5_8_5_9 ))
     :effect (and
        (not (at_5_8 ))
        (at_5_9 )
        (visited_5_9 ))
    )


    (:action move_5_9_5_8
     :parameters ()
     :precondition (and (at_5_9 ) (connected_5_9_5_8 ))
     :effect (and
        (not (at_5_9 ))
        (at_5_8 )
        (visited_5_8 ))
    )


    (:action move_6_0_6_1
     :parameters ()
     :precondition (and (at_6_0 ) (connected_6_0_6_1 ))
     :effect (and
        (not (at_6_0 ))
        (at_6_1 )
        (visited_6_1 ))
    )


    (:action move_6_1_6_0
     :parameters ()
     :precondition (and (at_6_1 ) (connected_6_1_6_0 ))
     :effect (and
        (not (at_6_1 ))
        (at_6_0 )
        (visited_6_0 ))
    )


    (:action move_6_1_6_2
     :parameters ()
     :precondition (and (at_6_1 ) (connected_6_1_6_2 ))
     :effect (and
        (not (at_6_1 ))
        (at_6_2 )
        (visited_6_2 ))
    )


    (:action move_6_2_6_1
     :parameters ()
     :precondition (and (at_6_2 ) (connected_6_2_6_1 ))
     :effect (and
        (not (at_6_2 ))
        (at_6_1 )
        (visited_6_1 ))
    )


    (:action move_6_2_6_3
     :parameters ()
     :precondition (and (at_6_2 ) (connected_6_2_6_3 ))
     :effect (and
        (not (at_6_2 ))
        (at_6_3 )
        (visited_6_3 ))
    )


    (:action move_6_3_6_2
     :parameters ()
     :precondition (and (at_6_3 ) (connected_6_3_6_2 ))
     :effect (and
        (not (at_6_3 ))
        (at_6_2 )
        (visited_6_2 ))
    )


    (:action move_6_3_6_4
     :parameters ()
     :precondition (and (at_6_3 ) (connected_6_3_6_4 ))
     :effect (and
        (not (at_6_3 ))
        (at_6_4 )
        (visited_6_4 ))
    )


    (:action move_6_4_6_3
     :parameters ()
     :precondition (and (at_6_4 ) (connected_6_4_6_3 ))
     :effect (and
        (not (at_6_4 ))
        (at_6_3 )
        (visited_6_3 ))
    )


    (:action move_6_4_6_5
     :parameters ()
     :precondition (and (at_6_4 ) (connected_6_4_6_5 ))
     :effect (and
        (not (at_6_4 ))
        (at_6_5 )
        (visited_6_5 ))
    )


    (:action move_6_5_6_4
     :parameters ()
     :precondition (and (at_6_5 ) (connected_6_5_6_4 ))
     :effect (and
        (not (at_6_5 ))
        (at_6_4 )
        (visited_6_4 ))
    )


    (:action move_6_5_6_6
     :parameters ()
     :precondition (and (at_6_5 ) (connected_6_5_6_6 ))
     :effect (and
        (not (at_6_5 ))
        (at_6_6 )
        (visited_6_6 ))
    )


    (:action move_6_6_6_5
     :parameters ()
     :precondition (and (at_6_6 ) (connected_6_6_6_5 ))
     :effect (and
        (not (at_6_6 ))
        (at_6_5 )
        (visited_6_5 ))
    )


    (:action move_6_6_6_7
     :parameters ()
     :precondition (and (at_6_6 ) (connected_6_6_6_7 ))
     :effect (and
        (not (at_6_6 ))
        (at_6_7 )
        (visited_6_7 ))
    )


    (:action move_6_7_6_6
     :parameters ()
     :precondition (and (at_6_7 ) (connected_6_7_6_6 ))
     :effect (and
        (not (at_6_7 ))
        (at_6_6 )
        (visited_6_6 ))
    )


    (:action move_6_7_6_8
     :parameters ()
     :precondition (and (at_6_7 ) (connected_6_7_6_8 ))
     :effect (and
        (not (at_6_7 ))
        (at_6_8 )
        (visited_6_8 ))
    )


    (:action move_6_8_6_7
     :parameters ()
     :precondition (and (at_6_8 ) (connected_6_8_6_7 ))
     :effect (and
        (not (at_6_8 ))
        (at_6_7 )
        (visited_6_7 ))
    )


    (:action move_6_8_6_9
     :parameters ()
     :precondition (and (at_6_8 ) (connected_6_8_6_9 ))
     :effect (and
        (not (at_6_8 ))
        (at_6_9 )
        (visited_6_9 ))
    )


    (:action move_6_9_6_8
     :parameters ()
     :precondition (and (at_6_9 ) (connected_6_9_6_8 ))
     :effect (and
        (not (at_6_9 ))
        (at_6_8 )
        (visited_6_8 ))
    )


    (:action move_7_0_7_1
     :parameters ()
     :precondition (and (at_7_0 ) (connected_7_0_7_1 ))
     :effect (and
        (not (at_7_0 ))
        (at_7_1 )
        (visited_7_1 ))
    )


    (:action move_7_1_7_0
     :parameters ()
     :precondition (and (at_7_1 ) (connected_7_1_7_0 ))
     :effect (and
        (not (at_7_1 ))
        (at_7_0 )
        (visited_7_0 ))
    )


    (:action move_7_1_7_2
     :parameters ()
     :precondition (and (at_7_1 ) (connected_7_1_7_2 ))
     :effect (and
        (not (at_7_1 ))
        (at_7_2 )
        (visited_7_2 ))
    )


    (:action move_7_2_7_1
     :parameters ()
     :precondition (and (at_7_2 ) (connected_7_2_7_1 ))
     :effect (and
        (not (at_7_2 ))
        (at_7_1 )
        (visited_7_1 ))
    )


    (:action move_7_2_7_3
     :parameters ()
     :precondition (and (at_7_2 ) (connected_7_2_7_3 ))
     :effect (and
        (not (at_7_2 ))
        (at_7_3 )
        (visited_7_3 ))
    )


    (:action move_7_3_7_2
     :parameters ()
     :precondition (and (at_7_3 ) (connected_7_3_7_2 ))
     :effect (and
        (not (at_7_3 ))
        (at_7_2 )
        (visited_7_2 ))
    )


    (:action move_7_3_7_4
     :parameters ()
     :precondition (and (at_7_3 ) (connected_7_3_7_4 ))
     :effect (and
        (not (at_7_3 ))
        (at_7_4 )
        (visited_7_4 ))
    )


    (:action move_7_4_7_3
     :parameters ()
     :precondition (and (at_7_4 ) (connected_7_4_7_3 ))
     :effect (and
        (not (at_7_4 ))
        (at_7_3 )
        (visited_7_3 ))
    )


    (:action move_7_4_7_5
     :parameters ()
     :precondition (and (at_7_4 ) (connected_7_4_7_5 ))
     :effect (and
        (not (at_7_4 ))
        (at_7_5 )
        (visited_7_5 ))
    )


    (:action move_7_5_7_4
     :parameters ()
     :precondition (and (at_7_5 ) (connected_7_5_7_4 ))
     :effect (and
        (not (at_7_5 ))
        (at_7_4 )
        (visited_7_4 ))
    )


    (:action move_7_5_7_6
     :parameters ()
     :precondition (and (at_7_5 ) (connected_7_5_7_6 ))
     :effect (and
        (not (at_7_5 ))
        (at_7_6 )
        (visited_7_6 ))
    )


    (:action move_7_6_7_5
     :parameters ()
     :precondition (and (at_7_6 ) (connected_7_6_7_5 ))
     :effect (and
        (not (at_7_6 ))
        (at_7_5 )
        (visited_7_5 ))
    )


    (:action move_7_6_7_7
     :parameters ()
     :precondition (and (at_7_6 ) (connected_7_6_7_7 ))
     :effect (and
        (not (at_7_6 ))
        (at_7_7 )
        (visited_7_7 ))
    )


    (:action move_7_7_7_6
     :parameters ()
     :precondition (and (at_7_7 ) (connected_7_7_7_6 ))
     :effect (and
        (not (at_7_7 ))
        (at_7_6 )
        (visited_7_6 ))
    )


    (:action move_7_7_7_8
     :parameters ()
     :precondition (and (at_7_7 ) (connected_7_7_7_8 ))
     :effect (and
        (not (at_7_7 ))
        (at_7_8 )
        (visited_7_8 ))
    )


    (:action move_7_8_7_7
     :parameters ()
     :precondition (and (at_7_8 ) (connected_7_8_7_7 ))
     :effect (and
        (not (at_7_8 ))
        (at_7_7 )
        (visited_7_7 ))
    )


    (:action move_7_8_7_9
     :parameters ()
     :precondition (and (at_7_8 ) (connected_7_8_7_9 ))
     :effect (and
        (not (at_7_8 ))
        (at_7_9 )
        (visited_7_9 ))
    )


    (:action move_7_9_7_8
     :parameters ()
     :precondition (and (at_7_9 ) (connected_7_9_7_8 ))
     :effect (and
        (not (at_7_9 ))
        (at_7_8 )
        (visited_7_8 ))
    )


    (:action move_8_0_8_1
     :parameters ()
     :precondition (and (at_8_0 ) (connected_8_0_8_1 ))
     :effect (and
        (not (at_8_0 ))
        (at_8_1 )
        (visited_8_1 ))
    )


    (:action move_8_1_8_0
     :parameters ()
     :precondition (and (at_8_1 ) (connected_8_1_8_0 ))
     :effect (and
        (not (at_8_1 ))
        (at_8_0 )
        (visited_8_0 ))
    )


    (:action move_8_1_8_2
     :parameters ()
     :precondition (and (at_8_1 ) (connected_8_1_8_2 ))
     :effect (and
        (not (at_8_1 ))
        (at_8_2 )
        (visited_8_2 ))
    )


    (:action move_8_2_8_1
     :parameters ()
     :precondition (and (at_8_2 ) (connected_8_2_8_1 ))
     :effect (and
        (not (at_8_2 ))
        (at_8_1 )
        (visited_8_1 ))
    )


    (:action move_8_2_8_3
     :parameters ()
     :precondition (and (at_8_2 ) (connected_8_2_8_3 ))
     :effect (and
        (not (at_8_2 ))
        (at_8_3 )
        (visited_8_3 ))
    )


    (:action move_8_3_8_2
     :parameters ()
     :precondition (and (at_8_3 ) (connected_8_3_8_2 ))
     :effect (and
        (not (at_8_3 ))
        (at_8_2 )
        (visited_8_2 ))
    )


    (:action move_8_3_8_4
     :parameters ()
     :precondition (and (at_8_3 ) (connected_8_3_8_4 ))
     :effect (and
        (not (at_8_3 ))
        (at_8_4 )
        (visited_8_4 ))
    )


    (:action move_8_4_8_3
     :parameters ()
     :precondition (and (at_8_4 ) (connected_8_4_8_3 ))
     :effect (and
        (not (at_8_4 ))
        (at_8_3 )
        (visited_8_3 ))
    )


    (:action move_8_4_8_5
     :parameters ()
     :precondition (and (at_8_4 ) (connected_8_4_8_5 ))
     :effect (and
        (not (at_8_4 ))
        (at_8_5 )
        (visited_8_5 ))
    )


    (:action move_8_5_8_4
     :parameters ()
     :precondition (and (at_8_5 ) (connected_8_5_8_4 ))
     :effect (and
        (not (at_8_5 ))
        (at_8_4 )
        (visited_8_4 ))
    )


    (:action move_8_5_8_6
     :parameters ()
     :precondition (and (at_8_5 ) (connected_8_5_8_6 ))
     :effect (and
        (not (at_8_5 ))
        (at_8_6 )
        (visited_8_6 ))
    )


    (:action move_8_6_8_5
     :parameters ()
     :precondition (and (at_8_6 ) (connected_8_6_8_5 ))
     :effect (and
        (not (at_8_6 ))
        (at_8_5 )
        (visited_8_5 ))
    )


    (:action move_8_6_8_7
     :parameters ()
     :precondition (and (at_8_6 ) (connected_8_6_8_7 ))
     :effect (and
        (not (at_8_6 ))
        (at_8_7 )
        (visited_8_7 ))
    )


    (:action move_8_7_8_6
     :parameters ()
     :precondition (and (at_8_7 ) (connected_8_7_8_6 ))
     :effect (and
        (not (at_8_7 ))
        (at_8_6 )
        (visited_8_6 ))
    )


    (:action move_8_7_8_8
     :parameters ()
     :precondition (and (at_8_7 ) (connected_8_7_8_8 ))
     :effect (and
        (not (at_8_7 ))
        (at_8_8 )
        (visited_8_8 ))
    )


    (:action move_8_8_8_7
     :parameters ()
     :precondition (and (at_8_8 ) (connected_8_8_8_7 ))
     :effect (and
        (not (at_8_8 ))
        (at_8_7 )
        (visited_8_7 ))
    )


    (:action move_8_8_8_9
     :parameters ()
     :precondition (and (at_8_8 ) (connected_8_8_8_9 ))
     :effect (and
        (not (at_8_8 ))
        (at_8_9 )
        (visited_8_9 ))
    )


    (:action move_8_9_8_8
     :parameters ()
     :precondition (and (at_8_9 ) (connected_8_9_8_8 ))
     :effect (and
        (not (at_8_9 ))
        (at_8_8 )
        (visited_8_8 ))
    )


    (:action move_9_0_9_1
     :parameters ()
     :precondition (and (at_9_0 ) (connected_9_0_9_1 ))
     :effect (and
        (not (at_9_0 ))
        (at_9_1 )
        (visited_9_1 ))
    )


    (:action move_9_1_9_0
     :parameters ()
     :precondition (and (at_9_1 ) (connected_9_1_9_0 ))
     :effect (and
        (not (at_9_1 ))
        (at_9_0 )
        (visited_9_0 ))
    )


    (:action move_9_1_9_2
     :parameters ()
     :precondition (and (at_9_1 ) (connected_9_1_9_2 ))
     :effect (and
        (not (at_9_1 ))
        (at_9_2 )
        (visited_9_2 ))
    )


    (:action move_9_2_9_1
     :parameters ()
     :precondition (and (at_9_2 ) (connected_9_2_9_1 ))
     :effect (and
        (not (at_9_2 ))
        (at_9_1 )
        (visited_9_1 ))
    )


    (:action move_9_2_9_3
     :parameters ()
     :precondition (and (at_9_2 ) (connected_9_2_9_3 ))
     :effect (and
        (not (at_9_2 ))
        (at_9_3 )
        (visited_9_3 ))
    )


    (:action move_9_3_9_2
     :parameters ()
     :precondition (and (at_9_3 ) (connected_9_3_9_2 ))
     :effect (and
        (not (at_9_3 ))
        (at_9_2 )
        (visited_9_2 ))
    )


    (:action move_9_3_9_4
     :parameters ()
     :precondition (and (at_9_3 ) (connected_9_3_9_4 ))
     :effect (and
        (not (at_9_3 ))
        (at_9_4 )
        (visited_9_4 ))
    )


    (:action move_9_4_9_3
     :parameters ()
     :precondition (and (at_9_4 ) (connected_9_4_9_3 ))
     :effect (and
        (not (at_9_4 ))
        (at_9_3 )
        (visited_9_3 ))
    )


    (:action move_9_4_9_5
     :parameters ()
     :precondition (and (at_9_4 ) (connected_9_4_9_5 ))
     :effect (and
        (not (at_9_4 ))
        (at_9_5 )
        (visited_9_5 ))
    )


    (:action move_9_5_9_4
     :parameters ()
     :precondition (and (at_9_5 ) (connected_9_5_9_4 ))
     :effect (and
        (not (at_9_5 ))
        (at_9_4 )
        (visited_9_4 ))
    )


    (:action move_9_5_9_6
     :parameters ()
     :precondition (and (at_9_5 ) (connected_9_5_9_6 ))
     :effect (and
        (not (at_9_5 ))
        (at_9_6 )
        (visited_9_6 ))
    )


    (:action move_9_6_9_5
     :parameters ()
     :precondition (and (at_9_6 ) (connected_9_6_9_5 ))
     :effect (and
        (not (at_9_6 ))
        (at_9_5 )
        (visited_9_5 ))
    )


    (:action move_9_6_9_7
     :parameters ()
     :precondition (and (at_9_6 ) (connected_9_6_9_7 ))
     :effect (and
        (not (at_9_6 ))
        (at_9_7 )
        (visited_9_7 ))
    )


    (:action move_9_7_9_6
     :parameters ()
     :precondition (and (at_9_7 ) (connected_9_7_9_6 ))
     :effect (and
        (not (at_9_7 ))
        (at_9_6 )
        (visited_9_6 ))
    )


    (:action move_9_7_9_8
     :parameters ()
     :precondition (and (at_9_7 ) (connected_9_7_9_8 ))
     :effect (and
        (not (at_9_7 ))
        (at_9_8 )
        (visited_9_8 ))
    )


    (:action move_9_8_9_7
     :parameters ()
     :precondition (and (at_9_8 ) (connected_9_8_9_7 ))
     :effect (and
        (not (at_9_8 ))
        (at_9_7 )
        (visited_9_7 ))
    )


    (:action move_9_8_9_9
     :parameters ()
     :precondition (and (at_9_8 ) (connected_9_8_9_9 ))
     :effect (and
        (not (at_9_8 ))
        (at_9_9 )
        (visited_9_9 ))
    )


    (:action move_9_9_9_8
     :parameters ()
     :precondition (and (at_9_9 ) (connected_9_9_9_8 ))
     :effect (and
        (not (at_9_9 ))
        (at_9_8 )
        (visited_9_8 ))
    )


    (:action move_0_0_1_0
     :parameters ()
     :precondition (and (at_0_0 ) (connected_0_0_1_0 ))
     :effect (and
        (not (at_0_0 ))
        (at_1_0 )
        (visited_1_0 ))
    )


    (:action move_1_0_0_0
     :parameters ()
     :precondition (and (at_1_0 ) (connected_1_0_0_0 ))
     :effect (and
        (not (at_1_0 ))
        (at_0_0 )
        (visited_0_0 ))
    )


    (:action move_0_1_1_1
     :parameters ()
     :precondition (and (at_0_1 ) (connected_0_1_1_1 ))
     :effect (and
        (not (at_0_1 ))
        (at_1_1 )
        (visited_1_1 ))
    )


    (:action move_1_1_0_1
     :parameters ()
     :precondition (and (at_1_1 ) (connected_1_1_0_1 ))
     :effect (and
        (not (at_1_1 ))
        (at_0_1 )
        (visited_0_1 ))
    )


    (:action move_0_2_1_2
     :parameters ()
     :precondition (and (at_0_2 ) (connected_0_2_1_2 ))
     :effect (and
        (not (at_0_2 ))
        (at_1_2 )
        (visited_1_2 ))
    )


    (:action move_1_2_0_2
     :parameters ()
     :precondition (and (at_1_2 ) (connected_1_2_0_2 ))
     :effect (and
        (not (at_1_2 ))
        (at_0_2 )
        (visited_0_2 ))
    )


    (:action move_0_3_1_3
     :parameters ()
     :precondition (and (at_0_3 ) (connected_0_3_1_3 ))
     :effect (and
        (not (at_0_3 ))
        (at_1_3 )
        (visited_1_3 ))
    )


    (:action move_1_3_0_3
     :parameters ()
     :precondition (and (at_1_3 ) (connected_1_3_0_3 ))
     :effect (and
        (not (at_1_3 ))
        (at_0_3 )
        (visited_0_3 ))
    )


    (:action move_0_4_1_4
     :parameters ()
     :precondition (and (at_0_4 ) (connected_0_4_1_4 ))
     :effect (and
        (not (at_0_4 ))
        (at_1_4 )
        (visited_1_4 ))
    )


    (:action move_1_4_0_4
     :parameters ()
     :precondition (and (at_1_4 ) (connected_1_4_0_4 ))
     :effect (and
        (not (at_1_4 ))
        (at_0_4 )
        (visited_0_4 ))
    )


    (:action move_0_5_1_5
     :parameters ()
     :precondition (and (at_0_5 ) (connected_0_5_1_5 ))
     :effect (and
        (not (at_0_5 ))
        (at_1_5 )
        (visited_1_5 ))
    )


    (:action move_1_5_0_5
     :parameters ()
     :precondition (and (at_1_5 ) (connected_1_5_0_5 ))
     :effect (and
        (not (at_1_5 ))
        (at_0_5 )
        (visited_0_5 ))
    )


    (:action move_0_6_1_6
     :parameters ()
     :precondition (and (at_0_6 ) (connected_0_6_1_6 ))
     :effect (and
        (not (at_0_6 ))
        (at_1_6 )
        (visited_1_6 ))
    )


    (:action move_1_6_0_6
     :parameters ()
     :precondition (and (at_1_6 ) (connected_1_6_0_6 ))
     :effect (and
        (not (at_1_6 ))
        (at_0_6 )
        (visited_0_6 ))
    )


    (:action move_0_7_1_7
     :parameters ()
     :precondition (and (at_0_7 ) (connected_0_7_1_7 ))
     :effect (and
        (not (at_0_7 ))
        (at_1_7 )
        (visited_1_7 ))
    )


    (:action move_1_7_0_7
     :parameters ()
     :precondition (and (at_1_7 ) (connected_1_7_0_7 ))
     :effect (and
        (not (at_1_7 ))
        (at_0_7 )
        (visited_0_7 ))
    )


    (:action move_0_8_1_8
     :parameters ()
     :precondition (and (at_0_8 ) (connected_0_8_1_8 ))
     :effect (and
        (not (at_0_8 ))
        (at_1_8 )
        (visited_1_8 ))
    )


    (:action move_1_8_0_8
     :parameters ()
     :precondition (and (at_1_8 ) (connected_1_8_0_8 ))
     :effect (and
        (not (at_1_8 ))
        (at_0_8 )
        (visited_0_8 ))
    )


    (:action move_0_9_1_9
     :parameters ()
     :precondition (and (at_0_9 ) (connected_0_9_1_9 ))
     :effect (and
        (not (at_0_9 ))
        (at_1_9 )
        (visited_1_9 ))
    )


    (:action move_1_9_0_9
     :parameters ()
     :precondition (and (at_1_9 ) (connected_1_9_0_9 ))
     :effect (and
        (not (at_1_9 ))
        (at_0_9 )
        (visited_0_9 ))
    )


    (:action move_1_0_2_0
     :parameters ()
     :precondition (and (at_1_0 ) (connected_1_0_2_0 ))
     :effect (and
        (not (at_1_0 ))
        (at_2_0 )
        (visited_2_0 ))
    )


    (:action move_2_0_1_0
     :parameters ()
     :precondition (and (at_2_0 ) (connected_2_0_1_0 ))
     :effect (and
        (not (at_2_0 ))
        (at_1_0 )
        (visited_1_0 ))
    )


    (:action move_1_1_2_1
     :parameters ()
     :precondition (and (at_1_1 ) (connected_1_1_2_1 ))
     :effect (and
        (not (at_1_1 ))
        (at_2_1 )
        (visited_2_1 ))
    )


    (:action move_2_1_1_1
     :parameters ()
     :precondition (and (at_2_1 ) (connected_2_1_1_1 ))
     :effect (and
        (not (at_2_1 ))
        (at_1_1 )
        (visited_1_1 ))
    )


    (:action move_1_2_2_2
     :parameters ()
     :precondition (and (at_1_2 ) (connected_1_2_2_2 ))
     :effect (and
        (not (at_1_2 ))
        (at_2_2 )
        (visited_2_2 ))
    )


    (:action move_2_2_1_2
     :parameters ()
     :precondition (and (at_2_2 ) (connected_2_2_1_2 ))
     :effect (and
        (not (at_2_2 ))
        (at_1_2 )
        (visited_1_2 ))
    )


    (:action move_1_3_2_3
     :parameters ()
     :precondition (and (at_1_3 ) (connected_1_3_2_3 ))
     :effect (and
        (not (at_1_3 ))
        (at_2_3 )
        (visited_2_3 ))
    )


    (:action move_2_3_1_3
     :parameters ()
     :precondition (and (at_2_3 ) (connected_2_3_1_3 ))
     :effect (and
        (not (at_2_3 ))
        (at_1_3 )
        (visited_1_3 ))
    )


    (:action move_1_4_2_4
     :parameters ()
     :precondition (and (at_1_4 ) (connected_1_4_2_4 ))
     :effect (and
        (not (at_1_4 ))
        (at_2_4 )
        (visited_2_4 ))
    )


    (:action move_2_4_1_4
     :parameters ()
     :precondition (and (at_2_4 ) (connected_2_4_1_4 ))
     :effect (and
        (not (at_2_4 ))
        (at_1_4 )
        (visited_1_4 ))
    )


    (:action move_1_5_2_5
     :parameters ()
     :precondition (and (at_1_5 ) (connected_1_5_2_5 ))
     :effect (and
        (not (at_1_5 ))
        (at_2_5 )
        (visited_2_5 ))
    )


    (:action move_2_5_1_5
     :parameters ()
     :precondition (and (at_2_5 ) (connected_2_5_1_5 ))
     :effect (and
        (not (at_2_5 ))
        (at_1_5 )
        (visited_1_5 ))
    )


    (:action move_1_6_2_6
     :parameters ()
     :precondition (and (at_1_6 ) (connected_1_6_2_6 ))
     :effect (and
        (not (at_1_6 ))
        (at_2_6 )
        (visited_2_6 ))
    )


    (:action move_2_6_1_6
     :parameters ()
     :precondition (and (at_2_6 ) (connected_2_6_1_6 ))
     :effect (and
        (not (at_2_6 ))
        (at_1_6 )
        (visited_1_6 ))
    )


    (:action move_1_7_2_7
     :parameters ()
     :precondition (and (at_1_7 ) (connected_1_7_2_7 ))
     :effect (and
        (not (at_1_7 ))
        (at_2_7 )
        (visited_2_7 ))
    )


    (:action move_2_7_1_7
     :parameters ()
     :precondition (and (at_2_7 ) (connected_2_7_1_7 ))
     :effect (and
        (not (at_2_7 ))
        (at_1_7 )
        (visited_1_7 ))
    )


    (:action move_1_8_2_8
     :parameters ()
     :precondition (and (at_1_8 ) (connected_1_8_2_8 ))
     :effect (and
        (not (at_1_8 ))
        (at_2_8 )
        (visited_2_8 ))
    )


    (:action move_2_8_1_8
     :parameters ()
     :precondition (and (at_2_8 ) (connected_2_8_1_8 ))
     :effect (and
        (not (at_2_8 ))
        (at_1_8 )
        (visited_1_8 ))
    )


    (:action move_1_9_2_9
     :parameters ()
     :precondition (and (at_1_9 ) (connected_1_9_2_9 ))
     :effect (and
        (not (at_1_9 ))
        (at_2_9 )
        (visited_2_9 ))
    )


    (:action move_2_9_1_9
     :parameters ()
     :precondition (and (at_2_9 ) (connected_2_9_1_9 ))
     :effect (and
        (not (at_2_9 ))
        (at_1_9 )
        (visited_1_9 ))
    )


    (:action move_2_0_3_0
     :parameters ()
     :precondition (and (at_2_0 ) (connected_2_0_3_0 ))
     :effect (and
        (not (at_2_0 ))
        (at_3_0 )
        (visited_3_0 ))
    )


    (:action move_3_0_2_0
     :parameters ()
     :precondition (and (at_3_0 ) (connected_3_0_2_0 ))
     :effect (and
        (not (at_3_0 ))
        (at_2_0 )
        (visited_2_0 ))
    )


    (:action move_2_1_3_1
     :parameters ()
     :precondition (and (at_2_1 ) (connected_2_1_3_1 ))
     :effect (and
        (not (at_2_1 ))
        (at_3_1 )
        (visited_3_1 ))
    )


    (:action move_3_1_2_1
     :parameters ()
     :precondition (and (at_3_1 ) (connected_3_1_2_1 ))
     :effect (and
        (not (at_3_1 ))
        (at_2_1 )
        (visited_2_1 ))
    )


    (:action move_2_2_3_2
     :parameters ()
     :precondition (and (at_2_2 ) (connected_2_2_3_2 ))
     :effect (and
        (not (at_2_2 ))
        (at_3_2 )
        (visited_3_2 ))
    )


    (:action move_3_2_2_2
     :parameters ()
     :precondition (and (at_3_2 ) (connected_3_2_2_2 ))
     :effect (and
        (not (at_3_2 ))
        (at_2_2 )
        (visited_2_2 ))
    )


    (:action move_2_3_3_3
     :parameters ()
     :precondition (and (at_2_3 ) (connected_2_3_3_3 ))
     :effect (and
        (not (at_2_3 ))
        (at_3_3 )
        (visited_3_3 ))
    )


    (:action move_3_3_2_3
     :parameters ()
     :precondition (and (at_3_3 ) (connected_3_3_2_3 ))
     :effect (and
        (not (at_3_3 ))
        (at_2_3 )
        (visited_2_3 ))
    )


    (:action move_2_4_3_4
     :parameters ()
     :precondition (and (at_2_4 ) (connected_2_4_3_4 ))
     :effect (and
        (not (at_2_4 ))
        (at_3_4 )
        (visited_3_4 ))
    )


    (:action move_3_4_2_4
     :parameters ()
     :precondition (and (at_3_4 ) (connected_3_4_2_4 ))
     :effect (and
        (not (at_3_4 ))
        (at_2_4 )
        (visited_2_4 ))
    )


    (:action move_2_5_3_5
     :parameters ()
     :precondition (and (at_2_5 ) (connected_2_5_3_5 ))
     :effect (and
        (not (at_2_5 ))
        (at_3_5 )
        (visited_3_5 ))
    )


    (:action move_3_5_2_5
     :parameters ()
     :precondition (and (at_3_5 ) (connected_3_5_2_5 ))
     :effect (and
        (not (at_3_5 ))
        (at_2_5 )
        (visited_2_5 ))
    )


    (:action move_2_6_3_6
     :parameters ()
     :precondition (and (at_2_6 ) (connected_2_6_3_6 ))
     :effect (and
        (not (at_2_6 ))
        (at_3_6 )
        (visited_3_6 ))
    )


    (:action move_3_6_2_6
     :parameters ()
     :precondition (and (at_3_6 ) (connected_3_6_2_6 ))
     :effect (and
        (not (at_3_6 ))
        (at_2_6 )
        (visited_2_6 ))
    )


    (:action move_2_7_3_7
     :parameters ()
     :precondition (and (at_2_7 ) (connected_2_7_3_7 ))
     :effect (and
        (not (at_2_7 ))
        (at_3_7 )
        (visited_3_7 ))
    )


    (:action move_3_7_2_7
     :parameters ()
     :precondition (and (at_3_7 ) (connected_3_7_2_7 ))
     :effect (and
        (not (at_3_7 ))
        (at_2_7 )
        (visited_2_7 ))
    )


    (:action move_2_8_3_8
     :parameters ()
     :precondition (and (at_2_8 ) (connected_2_8_3_8 ))
     :effect (and
        (not (at_2_8 ))
        (at_3_8 )
        (visited_3_8 ))
    )


    (:action move_3_8_2_8
     :parameters ()
     :precondition (and (at_3_8 ) (connected_3_8_2_8 ))
     :effect (and
        (not (at_3_8 ))
        (at_2_8 )
        (visited_2_8 ))
    )


    (:action move_2_9_3_9
     :parameters ()
     :precondition (and (at_2_9 ) (connected_2_9_3_9 ))
     :effect (and
        (not (at_2_9 ))
        (at_3_9 )
        (visited_3_9 ))
    )


    (:action move_3_9_2_9
     :parameters ()
     :precondition (and (at_3_9 ) (connected_3_9_2_9 ))
     :effect (and
        (not (at_3_9 ))
        (at_2_9 )
        (visited_2_9 ))
    )


    (:action move_3_0_4_0
     :parameters ()
     :precondition (and (at_3_0 ) (connected_3_0_4_0 ))
     :effect (and
        (not (at_3_0 ))
        (at_4_0 )
        (visited_4_0 ))
    )


    (:action move_4_0_3_0
     :parameters ()
     :precondition (and (at_4_0 ) (connected_4_0_3_0 ))
     :effect (and
        (not (at_4_0 ))
        (at_3_0 )
        (visited_3_0 ))
    )


    (:action move_3_1_4_1
     :parameters ()
     :precondition (and (at_3_1 ) (connected_3_1_4_1 ))
     :effect (and
        (not (at_3_1 ))
        (at_4_1 )
        (visited_4_1 ))
    )


    (:action move_4_1_3_1
     :parameters ()
     :precondition (and (at_4_1 ) (connected_4_1_3_1 ))
     :effect (and
        (not (at_4_1 ))
        (at_3_1 )
        (visited_3_1 ))
    )


    (:action move_3_2_4_2
     :parameters ()
     :precondition (and (at_3_2 ) (connected_3_2_4_2 ))
     :effect (and
        (not (at_3_2 ))
        (at_4_2 )
        (visited_4_2 ))
    )


    (:action move_4_2_3_2
     :parameters ()
     :precondition (and (at_4_2 ) (connected_4_2_3_2 ))
     :effect (and
        (not (at_4_2 ))
        (at_3_2 )
        (visited_3_2 ))
    )


    (:action move_3_3_4_3
     :parameters ()
     :precondition (and (at_3_3 ) (connected_3_3_4_3 ))
     :effect (and
        (not (at_3_3 ))
        (at_4_3 )
        (visited_4_3 ))
    )


    (:action move_4_3_3_3
     :parameters ()
     :precondition (and (at_4_3 ) (connected_4_3_3_3 ))
     :effect (and
        (not (at_4_3 ))
        (at_3_3 )
        (visited_3_3 ))
    )


    (:action move_3_4_4_4
     :parameters ()
     :precondition (and (at_3_4 ) (connected_3_4_4_4 ))
     :effect (and
        (not (at_3_4 ))
        (at_4_4 )
        (visited_4_4 ))
    )


    (:action move_4_4_3_4
     :parameters ()
     :precondition (and (at_4_4 ) (connected_4_4_3_4 ))
     :effect (and
        (not (at_4_4 ))
        (at_3_4 )
        (visited_3_4 ))
    )


    (:action move_3_5_4_5
     :parameters ()
     :precondition (and (at_3_5 ) (connected_3_5_4_5 ))
     :effect (and
        (not (at_3_5 ))
        (at_4_5 )
        (visited_4_5 ))
    )


    (:action move_4_5_3_5
     :parameters ()
     :precondition (and (at_4_5 ) (connected_4_5_3_5 ))
     :effect (and
        (not (at_4_5 ))
        (at_3_5 )
        (visited_3_5 ))
    )


    (:action move_3_6_4_6
     :parameters ()
     :precondition (and (at_3_6 ) (connected_3_6_4_6 ))
     :effect (and
        (not (at_3_6 ))
        (at_4_6 )
        (visited_4_6 ))
    )


    (:action move_4_6_3_6
     :parameters ()
     :precondition (and (at_4_6 ) (connected_4_6_3_6 ))
     :effect (and
        (not (at_4_6 ))
        (at_3_6 )
        (visited_3_6 ))
    )


    (:action move_3_7_4_7
     :parameters ()
     :precondition (and (at_3_7 ) (connected_3_7_4_7 ))
     :effect (and
        (not (at_3_7 ))
        (at_4_7 )
        (visited_4_7 ))
    )


    (:action move_4_7_3_7
     :parameters ()
     :precondition (and (at_4_7 ) (connected_4_7_3_7 ))
     :effect (and
        (not (at_4_7 ))
        (at_3_7 )
        (visited_3_7 ))
    )


    (:action move_3_8_4_8
     :parameters ()
     :precondition (and (at_3_8 ) (connected_3_8_4_8 ))
     :effect (and
        (not (at_3_8 ))
        (at_4_8 )
        (visited_4_8 ))
    )


    (:action move_4_8_3_8
     :parameters ()
     :precondition (and (at_4_8 ) (connected_4_8_3_8 ))
     :effect (and
        (not (at_4_8 ))
        (at_3_8 )
        (visited_3_8 ))
    )


    (:action move_3_9_4_9
     :parameters ()
     :precondition (and (at_3_9 ) (connected_3_9_4_9 ))
     :effect (and
        (not (at_3_9 ))
        (at_4_9 )
        (visited_4_9 ))
    )


    (:action move_4_9_3_9
     :parameters ()
     :precondition (and (at_4_9 ) (connected_4_9_3_9 ))
     :effect (and
        (not (at_4_9 ))
        (at_3_9 )
        (visited_3_9 ))
    )


    (:action move_4_0_5_0
     :parameters ()
     :precondition (and (at_4_0 ) (connected_4_0_5_0 ))
     :effect (and
        (not (at_4_0 ))
        (at_5_0 )
        (visited_5_0 ))
    )


    (:action move_5_0_4_0
     :parameters ()
     :precondition (and (at_5_0 ) (connected_5_0_4_0 ))
     :effect (and
        (not (at_5_0 ))
        (at_4_0 )
        (visited_4_0 ))
    )


    (:action move_4_1_5_1
     :parameters ()
     :precondition (and (at_4_1 ) (connected_4_1_5_1 ))
     :effect (and
        (not (at_4_1 ))
        (at_5_1 )
        (visited_5_1 ))
    )


    (:action move_5_1_4_1
     :parameters ()
     :precondition (and (at_5_1 ) (connected_5_1_4_1 ))
     :effect (and
        (not (at_5_1 ))
        (at_4_1 )
        (visited_4_1 ))
    )


    (:action move_4_2_5_2
     :parameters ()
     :precondition (and (at_4_2 ) (connected_4_2_5_2 ))
     :effect (and
        (not (at_4_2 ))
        (at_5_2 )
        (visited_5_2 ))
    )


    (:action move_5_2_4_2
     :parameters ()
     :precondition (and (at_5_2 ) (connected_5_2_4_2 ))
     :effect (and
        (not (at_5_2 ))
        (at_4_2 )
        (visited_4_2 ))
    )


    (:action move_4_3_5_3
     :parameters ()
     :precondition (and (at_4_3 ) (connected_4_3_5_3 ))
     :effect (and
        (not (at_4_3 ))
        (at_5_3 )
        (visited_5_3 ))
    )


    (:action move_5_3_4_3
     :parameters ()
     :precondition (and (at_5_3 ) (connected_5_3_4_3 ))
     :effect (and
        (not (at_5_3 ))
        (at_4_3 )
        (visited_4_3 ))
    )


    (:action move_4_4_5_4
     :parameters ()
     :precondition (and (at_4_4 ) (connected_4_4_5_4 ))
     :effect (and
        (not (at_4_4 ))
        (at_5_4 )
        (visited_5_4 ))
    )


    (:action move_5_4_4_4
     :parameters ()
     :precondition (and (at_5_4 ) (connected_5_4_4_4 ))
     :effect (and
        (not (at_5_4 ))
        (at_4_4 )
        (visited_4_4 ))
    )


    (:action move_4_5_5_5
     :parameters ()
     :precondition (and (at_4_5 ) (connected_4_5_5_5 ))
     :effect (and
        (not (at_4_5 ))
        (at_5_5 )
        (visited_5_5 ))
    )


    (:action move_5_5_4_5
     :parameters ()
     :precondition (and (at_5_5 ) (connected_5_5_4_5 ))
     :effect (and
        (not (at_5_5 ))
        (at_4_5 )
        (visited_4_5 ))
    )


    (:action move_4_6_5_6
     :parameters ()
     :precondition (and (at_4_6 ) (connected_4_6_5_6 ))
     :effect (and
        (not (at_4_6 ))
        (at_5_6 )
        (visited_5_6 ))
    )


    (:action move_5_6_4_6
     :parameters ()
     :precondition (and (at_5_6 ) (connected_5_6_4_6 ))
     :effect (and
        (not (at_5_6 ))
        (at_4_6 )
        (visited_4_6 ))
    )


    (:action move_4_7_5_7
     :parameters ()
     :precondition (and (at_4_7 ) (connected_4_7_5_7 ))
     :effect (and
        (not (at_4_7 ))
        (at_5_7 )
        (visited_5_7 ))
    )


    (:action move_5_7_4_7
     :parameters ()
     :precondition (and (at_5_7 ) (connected_5_7_4_7 ))
     :effect (and
        (not (at_5_7 ))
        (at_4_7 )
        (visited_4_7 ))
    )


    (:action move_4_8_5_8
     :parameters ()
     :precondition (and (at_4_8 ) (connected_4_8_5_8 ))
     :effect (and
        (not (at_4_8 ))
        (at_5_8 )
        (visited_5_8 ))
    )


    (:action move_5_8_4_8
     :parameters ()
     :precondition (and (at_5_8 ) (connected_5_8_4_8 ))
     :effect (and
        (not (at_5_8 ))
        (at_4_8 )
        (visited_4_8 ))
    )


    (:action move_4_9_5_9
     :parameters ()
     :precondition (and (at_4_9 ) (connected_4_9_5_9 ))
     :effect (and
        (not (at_4_9 ))
        (at_5_9 )
        (visited_5_9 ))
    )


    (:action move_5_9_4_9
     :parameters ()
     :precondition (and (at_5_9 ) (connected_5_9_4_9 ))
     :effect (and
        (not (at_5_9 ))
        (at_4_9 )
        (visited_4_9 ))
    )


    (:action move_5_0_6_0
     :parameters ()
     :precondition (and (at_5_0 ) (connected_5_0_6_0 ))
     :effect (and
        (not (at_5_0 ))
        (at_6_0 )
        (visited_6_0 ))
    )


    (:action move_6_0_5_0
     :parameters ()
     :precondition (and (at_6_0 ) (connected_6_0_5_0 ))
     :effect (and
        (not (at_6_0 ))
        (at_5_0 )
        (visited_5_0 ))
    )


    (:action move_5_1_6_1
     :parameters ()
     :precondition (and (at_5_1 ) (connected_5_1_6_1 ))
     :effect (and
        (not (at_5_1 ))
        (at_6_1 )
        (visited_6_1 ))
    )


    (:action move_6_1_5_1
     :parameters ()
     :precondition (and (at_6_1 ) (connected_6_1_5_1 ))
     :effect (and
        (not (at_6_1 ))
        (at_5_1 )
        (visited_5_1 ))
    )


    (:action move_5_2_6_2
     :parameters ()
     :precondition (and (at_5_2 ) (connected_5_2_6_2 ))
     :effect (and
        (not (at_5_2 ))
        (at_6_2 )
        (visited_6_2 ))
    )


    (:action move_6_2_5_2
     :parameters ()
     :precondition (and (at_6_2 ) (connected_6_2_5_2 ))
     :effect (and
        (not (at_6_2 ))
        (at_5_2 )
        (visited_5_2 ))
    )


    (:action move_5_3_6_3
     :parameters ()
     :precondition (and (at_5_3 ) (connected_5_3_6_3 ))
     :effect (and
        (not (at_5_3 ))
        (at_6_3 )
        (visited_6_3 ))
    )


    (:action move_6_3_5_3
     :parameters ()
     :precondition (and (at_6_3 ) (connected_6_3_5_3 ))
     :effect (and
        (not (at_6_3 ))
        (at_5_3 )
        (visited_5_3 ))
    )


    (:action move_5_4_6_4
     :parameters ()
     :precondition (and (at_5_4 ) (connected_5_4_6_4 ))
     :effect (and
        (not (at_5_4 ))
        (at_6_4 )
        (visited_6_4 ))
    )


    (:action move_6_4_5_4
     :parameters ()
     :precondition (and (at_6_4 ) (connected_6_4_5_4 ))
     :effect (and
        (not (at_6_4 ))
        (at_5_4 )
        (visited_5_4 ))
    )


    (:action move_5_5_6_5
     :parameters ()
     :precondition (and (at_5_5 ) (connected_5_5_6_5 ))
     :effect (and
        (not (at_5_5 ))
        (at_6_5 )
        (visited_6_5 ))
    )


    (:action move_6_5_5_5
     :parameters ()
     :precondition (and (at_6_5 ) (connected_6_5_5_5 ))
     :effect (and
        (not (at_6_5 ))
        (at_5_5 )
        (visited_5_5 ))
    )


    (:action move_5_6_6_6
     :parameters ()
     :precondition (and (at_5_6 ) (connected_5_6_6_6 ))
     :effect (and
        (not (at_5_6 ))
        (at_6_6 )
        (visited_6_6 ))
    )


    (:action move_6_6_5_6
     :parameters ()
     :precondition (and (at_6_6 ) (connected_6_6_5_6 ))
     :effect (and
        (not (at_6_6 ))
        (at_5_6 )
        (visited_5_6 ))
    )


    (:action move_5_7_6_7
     :parameters ()
     :precondition (and (at_5_7 ) (connected_5_7_6_7 ))
     :effect (and
        (not (at_5_7 ))
        (at_6_7 )
        (visited_6_7 ))
    )


    (:action move_6_7_5_7
     :parameters ()
     :precondition (and (at_6_7 ) (connected_6_7_5_7 ))
     :effect (and
        (not (at_6_7 ))
        (at_5_7 )
        (visited_5_7 ))
    )


    (:action move_5_8_6_8
     :parameters ()
     :precondition (and (at_5_8 ) (connected_5_8_6_8 ))
     :effect (and
        (not (at_5_8 ))
        (at_6_8 )
        (visited_6_8 ))
    )


    (:action move_6_8_5_8
     :parameters ()
     :precondition (and (at_6_8 ) (connected_6_8_5_8 ))
     :effect (and
        (not (at_6_8 ))
        (at_5_8 )
        (visited_5_8 ))
    )


    (:action move_5_9_6_9
     :parameters ()
     :precondition (and (at_5_9 ) (connected_5_9_6_9 ))
     :effect (and
        (not (at_5_9 ))
        (at_6_9 )
        (visited_6_9 ))
    )


    (:action move_6_9_5_9
     :parameters ()
     :precondition (and (at_6_9 ) (connected_6_9_5_9 ))
     :effect (and
        (not (at_6_9 ))
        (at_5_9 )
        (visited_5_9 ))
    )


    (:action move_6_0_7_0
     :parameters ()
     :precondition (and (at_6_0 ) (connected_6_0_7_0 ))
     :effect (and
        (not (at_6_0 ))
        (at_7_0 )
        (visited_7_0 ))
    )


    (:action move_7_0_6_0
     :parameters ()
     :precondition (and (at_7_0 ) (connected_7_0_6_0 ))
     :effect (and
        (not (at_7_0 ))
        (at_6_0 )
        (visited_6_0 ))
    )


    (:action move_6_1_7_1
     :parameters ()
     :precondition (and (at_6_1 ) (connected_6_1_7_1 ))
     :effect (and
        (not (at_6_1 ))
        (at_7_1 )
        (visited_7_1 ))
    )


    (:action move_7_1_6_1
     :parameters ()
     :precondition (and (at_7_1 ) (connected_7_1_6_1 ))
     :effect (and
        (not (at_7_1 ))
        (at_6_1 )
        (visited_6_1 ))
    )


    (:action move_6_2_7_2
     :parameters ()
     :precondition (and (at_6_2 ) (connected_6_2_7_2 ))
     :effect (and
        (not (at_6_2 ))
        (at_7_2 )
        (visited_7_2 ))
    )


    (:action move_7_2_6_2
     :parameters ()
     :precondition (and (at_7_2 ) (connected_7_2_6_2 ))
     :effect (and
        (not (at_7_2 ))
        (at_6_2 )
        (visited_6_2 ))
    )


    (:action move_6_3_7_3
     :parameters ()
     :precondition (and (at_6_3 ) (connected_6_3_7_3 ))
     :effect (and
        (not (at_6_3 ))
        (at_7_3 )
        (visited_7_3 ))
    )


    (:action move_7_3_6_3
     :parameters ()
     :precondition (and (at_7_3 ) (connected_7_3_6_3 ))
     :effect (and
        (not (at_7_3 ))
        (at_6_3 )
        (visited_6_3 ))
    )


    (:action move_6_4_7_4
     :parameters ()
     :precondition (and (at_6_4 ) (connected_6_4_7_4 ))
     :effect (and
        (not (at_6_4 ))
        (at_7_4 )
        (visited_7_4 ))
    )


    (:action move_7_4_6_4
     :parameters ()
     :precondition (and (at_7_4 ) (connected_7_4_6_4 ))
     :effect (and
        (not (at_7_4 ))
        (at_6_4 )
        (visited_6_4 ))
    )


    (:action move_6_5_7_5
     :parameters ()
     :precondition (and (at_6_5 ) (connected_6_5_7_5 ))
     :effect (and
        (not (at_6_5 ))
        (at_7_5 )
        (visited_7_5 ))
    )


    (:action move_7_5_6_5
     :parameters ()
     :precondition (and (at_7_5 ) (connected_7_5_6_5 ))
     :effect (and
        (not (at_7_5 ))
        (at_6_5 )
        (visited_6_5 ))
    )


    (:action move_6_6_7_6
     :parameters ()
     :precondition (and (at_6_6 ) (connected_6_6_7_6 ))
     :effect (and
        (not (at_6_6 ))
        (at_7_6 )
        (visited_7_6 ))
    )


    (:action move_7_6_6_6
     :parameters ()
     :precondition (and (at_7_6 ) (connected_7_6_6_6 ))
     :effect (and
        (not (at_7_6 ))
        (at_6_6 )
        (visited_6_6 ))
    )


    (:action move_6_7_7_7
     :parameters ()
     :precondition (and (at_6_7 ) (connected_6_7_7_7 ))
     :effect (and
        (not (at_6_7 ))
        (at_7_7 )
        (visited_7_7 ))
    )


    (:action move_7_7_6_7
     :parameters ()
     :precondition (and (at_7_7 ) (connected_7_7_6_7 ))
     :effect (and
        (not (at_7_7 ))
        (at_6_7 )
        (visited_6_7 ))
    )


    (:action move_6_8_7_8
     :parameters ()
     :precondition (and (at_6_8 ) (connected_6_8_7_8 ))
     :effect (and
        (not (at_6_8 ))
        (at_7_8 )
        (visited_7_8 ))
    )


    (:action move_7_8_6_8
     :parameters ()
     :precondition (and (at_7_8 ) (connected_7_8_6_8 ))
     :effect (and
        (not (at_7_8 ))
        (at_6_8 )
        (visited_6_8 ))
    )


    (:action move_6_9_7_9
     :parameters ()
     :precondition (and (at_6_9 ) (connected_6_9_7_9 ))
     :effect (and
        (not (at_6_9 ))
        (at_7_9 )
        (visited_7_9 ))
    )


    (:action move_7_9_6_9
     :parameters ()
     :precondition (and (at_7_9 ) (connected_7_9_6_9 ))
     :effect (and
        (not (at_7_9 ))
        (at_6_9 )
        (visited_6_9 ))
    )


    (:action move_7_0_8_0
     :parameters ()
     :precondition (and (at_7_0 ) (connected_7_0_8_0 ))
     :effect (and
        (not (at_7_0 ))
        (at_8_0 )
        (visited_8_0 ))
    )


    (:action move_8_0_7_0
     :parameters ()
     :precondition (and (at_8_0 ) (connected_8_0_7_0 ))
     :effect (and
        (not (at_8_0 ))
        (at_7_0 )
        (visited_7_0 ))
    )


    (:action move_7_1_8_1
     :parameters ()
     :precondition (and (at_7_1 ) (connected_7_1_8_1 ))
     :effect (and
        (not (at_7_1 ))
        (at_8_1 )
        (visited_8_1 ))
    )


    (:action move_8_1_7_1
     :parameters ()
     :precondition (and (at_8_1 ) (connected_8_1_7_1 ))
     :effect (and
        (not (at_8_1 ))
        (at_7_1 )
        (visited_7_1 ))
    )


    (:action move_7_2_8_2
     :parameters ()
     :precondition (and (at_7_2 ) (connected_7_2_8_2 ))
     :effect (and
        (not (at_7_2 ))
        (at_8_2 )
        (visited_8_2 ))
    )


    (:action move_8_2_7_2
     :parameters ()
     :precondition (and (at_8_2 ) (connected_8_2_7_2 ))
     :effect (and
        (not (at_8_2 ))
        (at_7_2 )
        (visited_7_2 ))
    )


    (:action move_7_3_8_3
     :parameters ()
     :precondition (and (at_7_3 ) (connected_7_3_8_3 ))
     :effect (and
        (not (at_7_3 ))
        (at_8_3 )
        (visited_8_3 ))
    )


    (:action move_8_3_7_3
     :parameters ()
     :precondition (and (at_8_3 ) (connected_8_3_7_3 ))
     :effect (and
        (not (at_8_3 ))
        (at_7_3 )
        (visited_7_3 ))
    )


    (:action move_7_4_8_4
     :parameters ()
     :precondition (and (at_7_4 ) (connected_7_4_8_4 ))
     :effect (and
        (not (at_7_4 ))
        (at_8_4 )
        (visited_8_4 ))
    )


    (:action move_8_4_7_4
     :parameters ()
     :precondition (and (at_8_4 ) (connected_8_4_7_4 ))
     :effect (and
        (not (at_8_4 ))
        (at_7_4 )
        (visited_7_4 ))
    )


    (:action move_7_5_8_5
     :parameters ()
     :precondition (and (at_7_5 ) (connected_7_5_8_5 ))
     :effect (and
        (not (at_7_5 ))
        (at_8_5 )
        (visited_8_5 ))
    )


    (:action move_8_5_7_5
     :parameters ()
     :precondition (and (at_8_5 ) (connected_8_5_7_5 ))
     :effect (and
        (not (at_8_5 ))
        (at_7_5 )
        (visited_7_5 ))
    )


    (:action move_7_6_8_6
     :parameters ()
     :precondition (and (at_7_6 ) (connected_7_6_8_6 ))
     :effect (and
        (not (at_7_6 ))
        (at_8_6 )
        (visited_8_6 ))
    )


    (:action move_8_6_7_6
     :parameters ()
     :precondition (and (at_8_6 ) (connected_8_6_7_6 ))
     :effect (and
        (not (at_8_6 ))
        (at_7_6 )
        (visited_7_6 ))
    )


    (:action move_7_7_8_7
     :parameters ()
     :precondition (and (at_7_7 ) (connected_7_7_8_7 ))
     :effect (and
        (not (at_7_7 ))
        (at_8_7 )
        (visited_8_7 ))
    )


    (:action move_8_7_7_7
     :parameters ()
     :precondition (and (at_8_7 ) (connected_8_7_7_7 ))
     :effect (and
        (not (at_8_7 ))
        (at_7_7 )
        (visited_7_7 ))
    )


    (:action move_7_8_8_8
     :parameters ()
     :precondition (and (at_7_8 ) (connected_7_8_8_8 ))
     :effect (and
        (not (at_7_8 ))
        (at_8_8 )
        (visited_8_8 ))
    )


    (:action move_8_8_7_8
     :parameters ()
     :precondition (and (at_8_8 ) (connected_8_8_7_8 ))
     :effect (and
        (not (at_8_8 ))
        (at_7_8 )
        (visited_7_8 ))
    )


    (:action move_7_9_8_9
     :parameters ()
     :precondition (and (at_7_9 ) (connected_7_9_8_9 ))
     :effect (and
        (not (at_7_9 ))
        (at_8_9 )
        (visited_8_9 ))
    )


    (:action move_8_9_7_9
     :parameters ()
     :precondition (and (at_8_9 ) (connected_8_9_7_9 ))
     :effect (and
        (not (at_8_9 ))
        (at_7_9 )
        (visited_7_9 ))
    )


    (:action move_8_0_9_0
     :parameters ()
     :precondition (and (at_8_0 ) (connected_8_0_9_0 ))
     :effect (and
        (not (at_8_0 ))
        (at_9_0 )
        (visited_9_0 ))
    )


    (:action move_9_0_8_0
     :parameters ()
     :precondition (and (at_9_0 ) (connected_9_0_8_0 ))
     :effect (and
        (not (at_9_0 ))
        (at_8_0 )
        (visited_8_0 ))
    )


    (:action move_8_1_9_1
     :parameters ()
     :precondition (and (at_8_1 ) (connected_8_1_9_1 ))
     :effect (and
        (not (at_8_1 ))
        (at_9_1 )
        (visited_9_1 ))
    )


    (:action move_9_1_8_1
     :parameters ()
     :precondition (and (at_9_1 ) (connected_9_1_8_1 ))
     :effect (and
        (not (at_9_1 ))
        (at_8_1 )
        (visited_8_1 ))
    )


    (:action move_8_2_9_2
     :parameters ()
     :precondition (and (at_8_2 ) (connected_8_2_9_2 ))
     :effect (and
        (not (at_8_2 ))
        (at_9_2 )
        (visited_9_2 ))
    )


    (:action move_9_2_8_2
     :parameters ()
     :precondition (and (at_9_2 ) (connected_9_2_8_2 ))
     :effect (and
        (not (at_9_2 ))
        (at_8_2 )
        (visited_8_2 ))
    )


    (:action move_8_3_9_3
     :parameters ()
     :precondition (and (at_8_3 ) (connected_8_3_9_3 ))
     :effect (and
        (not (at_8_3 ))
        (at_9_3 )
        (visited_9_3 ))
    )


    (:action move_9_3_8_3
     :parameters ()
     :precondition (and (at_9_3 ) (connected_9_3_8_3 ))
     :effect (and
        (not (at_9_3 ))
        (at_8_3 )
        (visited_8_3 ))
    )


    (:action move_8_4_9_4
     :parameters ()
     :precondition (and (at_8_4 ) (connected_8_4_9_4 ))
     :effect (and
        (not (at_8_4 ))
        (at_9_4 )
        (visited_9_4 ))
    )


    (:action move_9_4_8_4
     :parameters ()
     :precondition (and (at_9_4 ) (connected_9_4_8_4 ))
     :effect (and
        (not (at_9_4 ))
        (at_8_4 )
        (visited_8_4 ))
    )


    (:action move_8_5_9_5
     :parameters ()
     :precondition (and (at_8_5 ) (connected_8_5_9_5 ))
     :effect (and
        (not (at_8_5 ))
        (at_9_5 )
        (visited_9_5 ))
    )


    (:action move_9_5_8_5
     :parameters ()
     :precondition (and (at_9_5 ) (connected_9_5_8_5 ))
     :effect (and
        (not (at_9_5 ))
        (at_8_5 )
        (visited_8_5 ))
    )


    (:action move_8_6_9_6
     :parameters ()
     :precondition (and (at_8_6 ) (connected_8_6_9_6 ))
     :effect (and
        (not (at_8_6 ))
        (at_9_6 )
        (visited_9_6 ))
    )


    (:action move_9_6_8_6
     :parameters ()
     :precondition (and (at_9_6 ) (connected_9_6_8_6 ))
     :effect (and
        (not (at_9_6 ))
        (at_8_6 )
        (visited_8_6 ))
    )


    (:action move_8_7_9_7
     :parameters ()
     :precondition (and (at_8_7 ) (connected_8_7_9_7 ))
     :effect (and
        (not (at_8_7 ))
        (at_9_7 )
        (visited_9_7 ))
    )


    (:action move_9_7_8_7
     :parameters ()
     :precondition (and (at_9_7 ) (connected_9_7_8_7 ))
     :effect (and
        (not (at_9_7 ))
        (at_8_7 )
        (visited_8_7 ))
    )


    (:action move_8_8_9_8
     :parameters ()
     :precondition (and (at_8_8 ) (connected_8_8_9_8 ))
     :effect (and
        (not (at_8_8 ))
        (at_9_8 )
        (visited_9_8 ))
    )


    (:action move_9_8_8_8
     :parameters ()
     :precondition (and (at_9_8 ) (connected_9_8_8_8 ))
     :effect (and
        (not (at_9_8 ))
        (at_8_8 )
        (visited_8_8 ))
    )


    (:action move_8_9_9_9
     :parameters ()
     :precondition (and (at_8_9 ) (connected_8_9_9_9 ))
     :effect (and
        (not (at_8_9 ))
        (at_9_9 )
        (visited_9_9 ))
    )


    (:action move_9_9_8_9
     :parameters ()
     :precondition (and (at_9_9 ) (connected_9_9_8_9 ))
     :effect (and
        (not (at_9_9 ))
        (at_8_9 )
        (visited_8_9 ))
    )

)